BookBLA/americano

src/main/java/com/bookbla/americano/base/config/SwaggerConfig.java, src/main/java/com/bookbla/americano/domain/auth/controller/AuthController.java, src/main/java/com/bookbla/americano/domain/auth/infra/kakao/KakaoOAuth2Provider.java, src/main/java/com/bookbla/americano/domain/auth/infra/kakao/dto/KakaoOAuth2MemberResponse.java
=> fix: 카카오 로그인 추가 및 스웨거 주소 변경

src/main/java/com/bookbla/americano/domain/member/enums/DateCostType.java, src/main/java/com/bookbla/americano/domain/member/enums/JustFriendType.java, src/test/java/com/bookbla/americano/domain/member/enums/DateCostTypeTest.java, src/test/java/com/bookbla/americano/domain/member/enums/JustFriendTypeTest.java, src/test/java/com/bookbla/americano/domain/member/service/MemberStyleServiceTest.java, src/test/java/com/bookbla/americano/domain/member/service/StyleServiceTest.java
=> fix: style 관련 문구 변경

src/main/java/com/bookbla/americano/domain/test/controller/TestController.java, src/main/java/com/bookbla/americano/domain/test/controller/dto/response/TestSignUpResponse.java
> 날 것 String으로 드리던 걸 Dto에 담아서 드리도록 하였어용
=> feat: 테스트 회원가입 응답을 Dto에 담아 전달

src/main/java/com/bookbla/americano/domain/member/controller/MemberLibraryController.java, src/main/java/com/bookbla/americano/domain/member/repository/PostcardRepository.java, src/main/java/com/bookbla/americano/domain/member/service/MemberLibraryService.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberLibraryServiceImpl.java, src/main/java/com/bookbla/americano/domain/quiz/repository/QuizReplyRepository.java
> 상대방 서재 조회 기능 제작
- 자신의 id, 상대방 id 로 매칭 여부를 확인하는 로직 제작
- isMatched가 true이면 프로필을 블러처리하지 않고 띄우도록 설계
> dev에서 최신버전을 받았는데 테스트 토큰 생성하는 방법을 잘 모르겠습니다. 그 로직에 문제가 없다면 잘 작동합니다.
> QuizReplyRepository 부분이 딸려들어간 것 같아요.. ㅠㅠ
=> Feat/target-library - 상대방 서재 조회 기능 제작 완료

src/main/java/com/bookbla/americano/domain/auth/controller/dto/response/LoginResponseDto.java, src/main/java/com/bookbla/americano/domain/auth/service/impl/AuthServiceImpl.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberProfile.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberSchedulerServiceImpl.java, src/main/java/com/bookbla/americano/domain/test/controller/TestController.java, src/main/java/com/bookbla/americano/domain/test/controller/dto/response/TestSignUpResponse.java
=> feat: 로그인 후 memberId를 추가로 반환 및 엽서 초기화 시간 변경

src/main/java/com/bookbla/americano/domain/member/service/impl/MemberAuthServiceImpl.java, src/main/resources/templates/verifyEmail.html
> 이메일 인증코드와 이메일 템플릿을 수정하였습니다!
>
=> Fix: 이메일 형식 수정

build.gradle, src/main/java/com/bookbla/americano/base/config/AuthConfig.java, src/main/java/com/bookbla/americano/base/interceptor/AdminInterceptor.java, src/main/java/com/bookbla/americano/domain/admin/controller/AdminController.java, src/main/java/com/bookbla/americano/domain/admin/controller/dto/request/AdminLoginRequest.java, src/main/java/com/bookbla/americano/domain/admin/controller/dto/request/AdminLogoutRequest.java, src/main/java/com/bookbla/americano/domain/admin/controller/dto/response/AdminLoginResponse.java, src/main/java/com/bookbla/americano/domain/admin/excpetion/AdminExceptionType.java, src/main/java/com/bookbla/americano/domain/admin/repository/AdminRepository.java, src/main/java/com/bookbla/americano/domain/admin/repository/AdminSessionRepository.java, src/main/java/com/bookbla/americano/domain/admin/repository/entity/Admin.java, src/main/java/com/bookbla/americano/domain/admin/repository/entity/AdminSession.java, src/main/java/com/bookbla/americano/domain/admin/service/AdminAuthService.java, src/main/java/com/bookbla/americano/domain/admin/service/BcryptPasswordEncoder.java, src/test/java/com/bookbla/americano/domain/admin/repository/entity/AdminSessionTest.java, src/test/java/com/bookbla/americano/domain/admin/repository/entity/AdminTest.java, src/test/java/com/bookbla/americano/domain/admin/service/AdminAuthServiceTest.java, src/test/java/com/bookbla/americano/domain/admin/service/PasswordEncoderTest.java
> 바쁜 일이 하나 끝나서.. 관리자 로그인 기능을 만들어보았습니다
회원의 인증 방식과 다른 인증 방식을 필요로 해서, 세션으로 만들어보았습니다
`Admin`, `AdminSession` 이렇게 두 개를 이용하도록 했어용
> 리액트와 next 알려주실 분 구합니다..
=> feat: 관리자 로그인 기능 구현

src/main/java/com/bookbla/americano/base/interceptor/AuthInterceptor.java
> Interceptor 내 Preflight 요청을 통과하는 로직을 추가한다
>
=> hotfix : pass preflight request in interceptor

build.gradle, src/main/java/com/bookbla/americano/AmericanoApplication.java, src/main/java/com/bookbla/americano/base/config/S3Config.java, src/main/java/com/bookbla/americano/domain/aws/controller/AwsController.java, src/main/java/com/bookbla/americano/domain/aws/controller/dto/response/S3PresignedUrlResponse.java, src/main/java/com/bookbla/americano/domain/aws/controller/enums/UploadType.java, src/main/java/com/bookbla/americano/domain/aws/enums/UploadType.java, src/main/java/com/bookbla/americano/domain/aws/exception/AwsException.java, src/main/java/com/bookbla/americano/domain/aws/exception/UploadTypeNotValidException.java, src/main/java/com/bookbla/americano/domain/aws/service/S3Service.java, src/main/java/com/bookbla/americano/domain/aws/service/impl/S3ServiceImpl.java
[개발] S3 파일 업로드를 위한 presignedUrl을 받아오는 API 구현
>
> 참고자료 : https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html
=> [개발] S3 파일 업로드를 위한 presignedUrl을 받아오는 API 구현

src/main/java/com/bookbla/americano/domain/member/enums/DrinkType.java, src/test/java/com/bookbla/americano/domain/member/enums/DrinkTypeTest.java, src/test/java/com/bookbla/americano/domain/member/service/MemberStyleServiceTest.java, src/test/java/com/bookbla/americano/domain/member/service/StyleServiceTest.java
>
주 1회 이상 -> 주 2회 이상
안마심 -> X
>
=> fix: 다시 변경된 음주 유형을 반영한다

.github/workflows/Deploy-dev.yml
=> fix: host 이름 주소 변경

src/main/java/com/bookbla/americano/domain/aws/enums/UploadType.java
이미지 수정 요청에 대한 타입을 추가하였습니다.
>
>
=> chore: Image upload 타입 추가

src/main/java/com/bookbla/americano/domain/member/service/impl/MemberEmailServiceImpl.java
> MemberEmail 객체가 수정이 안되고 생성만 되는 버그를 수정하였습니다!
>
=> fix: MemberEmail 업데이트 버그 수정

src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberProfileResponse.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberProfile.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberProfileServiceImpl.java
=> Hotfix: MemberProfile URL 컬럼 길이 변경

src/main/java/com/bookbla/americano/domain/member/service/impl/MemberBookServiceImpl.java, src/main/java/com/bookbla/americano/domain/memberask/service/MemberAskService.java, src/main/java/com/bookbla/americano/domain/memberask/service/impl/MemberAskServiceImpl.java, src/main/java/com/bookbla/americano/domain/quiz/controller/QuizController.java, src/main/java/com/bookbla/americano/domain/quiz/repository/QuizQuestionRepository.java
=> hotfix: 책 삭제시 퀴즈도 같이 삭제되도록 추가

src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberPostcard.java, src/main/java/com/bookbla/americano/domain/memberask/repository/MemberReplyRepository.java, src/main/java/com/bookbla/americano/domain/postcard/controller/PostcardController.java, src/main/java/com/bookbla/americano/domain/postcard/exception/PostcardExceptionType.java, src/main/java/com/bookbla/americano/domain/postcard/repository/PostcardTypeRepository.java, src/main/java/com/bookbla/americano/domain/postcard/repository/entity/Postcard.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java, src/main/java/com/bookbla/americano/domain/postcard/service/dto/request/SendPostcardRequest.java, src/main/java/com/bookbla/americano/domain/postcard/service/dto/response/PostcardTypeResponse.java, src/main/java/com/bookbla/americano/domain/postcard/service/dto/response/SendPostcardResponse.java, src/main/java/com/bookbla/americano/domain/postcard/service/impl/PostcardServiceImpl.java, src/main/java/com/bookbla/americano/domain/quiz/repository/entity/QuizReply.java
> 8.2 엽서 보내기 제작했습니다.
다음과 같은 방식으로 동작합니다.
1. memberReply 저장
2. 반복문을 돌면서 퀴즈 채점 quizQuestion
3. isCorrectFlag가 true라면 postcard 생성 후 PENDING 상태로 설정
4. SendPostcardResponse객체에 전송 성공 여부를 담아서 리턴
> 몇 가지 질문이 있습니다.
1. postcard_type의 용도가 궁금합니다. 지금은 일단 requset body에 postcard_type id를 담아서 주는 걸로 임시로 만들어 두긴 했는데. 그런 용도가 아닌듯 합니다.
5. postcard에 들어갈 image url은 프론트에서 보내주는건가요? 어디서 처리해야되나요? 일단 프론트에서 url보내주는 방식으로 구현했습니다.
6. quiz_reply_id는 여러개의 문제를 맞춰도, 하나만 담아지면 되는건가요? 일단 이부분을 빼고 구현했는데 빼는건 어떤가요?
=> Feat - send postcard 제작

src/main/java/com/bookbla/americano/domain/member/controller/MemberController.java
=> fix: Member API에서 AuthInterceptor가 빠진 부분 변경

src/main/java/com/bookbla/americano/domain/auth/controller/AuthController.java, src/main/java/com/bookbla/americano/domain/auth/controller/dto/request/RejoinRequest.java, src/main/java/com/bookbla/americano/domain/auth/controller/dto/response/RejoinResponse.java, src/main/java/com/bookbla/americano/domain/auth/exception/LoginExceptionType.java, src/main/java/com/bookbla/americano/domain/auth/infra/apple/dto/AppleOAuth2MemberResponse.java, src/main/java/com/bookbla/americano/domain/auth/infra/kakao/dto/KakaoOAuth2MemberResponse.java, src/main/java/com/bookbla/americano/domain/auth/service/AuthService.java, src/main/java/com/bookbla/americano/domain/auth/service/impl/AuthServiceImpl.java, src/main/java/com/bookbla/americano/domain/member/controller/MemberController.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberDeleteResponse.java, src/main/java/com/bookbla/americano/domain/member/enums/MemberStatus.java, src/main/java/com/bookbla/americano/domain/member/exception/MemberExceptionType.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/Member.java, src/main/java/com/bookbla/americano/domain/member/service/MemberService.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberServiceImpl.java, src/main/java/com/bookbla/americano/domain/test/service/impl/TestServiceImpl.java
1. 회원 탈퇴시 탈퇴 시점을 저장하는 `deleteAt`  컬럼 추가
2. 탈퇴한 회원 로그인할 시 로그인 불가
3. 탈퇴한 회원 재가입할 시,
a. 30일 이전이면 재가입 불가
b. 30일 이후이면 재가입 가능
> 
>
=> Feat: 회원 탈퇴 기능 구현

src/main/java/com/bookbla/americano/base/config/AuthConfig.java, src/main/java/com/bookbla/americano/domain/aws/controller/AwsController.java, src/main/java/com/bookbla/americano/domain/aws/enums/UploadType.java
> 프로필 사진 최초 등록 시 토큰이 없기 떄문에 제외 처리
>
=> feat: Aws/s3 api 토큰 검증 제외 처리

src/main/java/com/bookbla/americano/domain/auth/infra/kakao/KakaoOAuth2Provider.java
=> Hotfix: 카카오 로그인 버그 수정

.github/workflows/Deploy-dev.yml, build.gradle, src/main/java/com/bookbla/americano/domain/fcm/controller/FcmController.java, src/main/java/com/bookbla/americano/domain/fcm/controller/dto/request/FcmMessage.java, src/main/java/com/bookbla/americano/domain/fcm/controller/dto/request/FcmRequest.java, src/main/java/com/bookbla/americano/domain/fcm/controller/dto/request/FcmTokenCreateRequest.java, src/main/java/com/bookbla/americano/domain/fcm/controller/dto/response/FcmResponse.java, src/main/java/com/bookbla/americano/domain/fcm/controller/dto/response/FcmTokenCreateResponse.java, src/main/java/com/bookbla/americano/domain/fcm/controller/dto/response/FcmTokenDeleteResponse.java, src/main/java/com/bookbla/americano/domain/fcm/exception/FcmExceptionType.java, src/main/java/com/bookbla/americano/domain/fcm/service/FcmService.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/Member.java
=> Feat: fcm 기능 추가

.github/workflows/Deploy-dev.yml
=> chore: mv action 추가

.github/workflows/Deploy-dev.yml
=> chore: json 생성 CI로 이동

src/main/java/com/bookbla/americano/domain/book/repository/entity/Book.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberBookCreateRequest.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberBookUpdateRequest.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberBookCreateResponse.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberBookReadResponse.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberBookReadResponses.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberBookServiceImpl.java
=> fix: 책 등록시 감상문과 퀴즈를 함께 입력하도록 수정

src/main/java/com/bookbla/americano/domain/member/service/impl/MemberBookServiceImpl.java
=> hotfix: 업데이트시 문제 정답 입력하도록 수정

src/main/java/com/bookbla/americano/domain/auth/infra/apple/AppleOAuth2Provider.java, src/main/java/com/bookbla/americano/domain/member/enums/MemberStatus.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/Member.java
> 에플 로그인시 애플에 제공해야하는 clientSecret 제작시 필요한 추가 값들을 설정하였음
>
=> fix: 애플 로그인 secret 제작시 설정값 추가

src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberLibraryProfileReadResponse.java
> 대표책 여부를 추가로 반환하도록 isRepresntative 필드를 추가
>
=> fix: 내 서재 책 조회시 대표책 여부를 추가로 반환

src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberBookReadResponse.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberBookServiceImpl.java, src/main/java/com/bookbla/americano/domain/quiz/controller/dto/response/QuizQuestionReadResponse.java, src/main/java/com/bookbla/americano/domain/quiz/service/impl/QuizQuestionServiceImpl.java
> 책 정보 조회시 감상문을 추가로 반환하도록 하였습니다
>
=> fix: 책 정보 조회시 감상문 추가로 반환!

src/main/java/com/bookbla/americano/domain/quiz/controller/QuizController.java, src/main/java/com/bookbla/americano/domain/quiz/controller/dto/request/QuizQuestionUpdateRequest.java, src/main/java/com/bookbla/americano/domain/quiz/service/impl/QuizQuestionServiceImpl.java
> 
간단하게 DTO 필드 하나 추가했습니다.
p.s) update dto는 모든 데이터(컬럼)에  빈 값 검증이 적절치 않아보입니다..
>
=> fix: quiz 업데이트에 한 줄 감상문 정보도 포함

src/main/java/com/bookbla/americano/domain/member/controller/MemberBookController.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberBookQuizUpdateRequest.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberBookReviewUpdateRequest.java, src/main/java/com/bookbla/americano/domain/member/service/MemberBookService.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberBookServiceImpl.java, src/main/java/com/bookbla/americano/domain/memberask/controller/MemberAskController.java, src/main/java/com/bookbla/americano/domain/quiz/service/impl/QuizQuestionServiceImpl.java
=> feat: 감상문 수정 API 및 책 퀴즈 수정 API 개별 구현

src/test/java/com/bookbla/americano/domain/admin/service/AdminMemberServiceTest.java
=> test: 테스트 케이스 추가

src/main/java/com/bookbla/americano/domain/member/repository/MemberEmailRepository.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberEmail.java, src/main/java/com/bookbla/americano/domain/member/service/MemberSchedulerService.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberSchedulerServiceImpl.java
> 매일 새벽 4시마다 임시 메일 테이블을 삭제하는 기능
>
=> Feat: MemberEmail 테이블 삭제 스케줄러 구현

build.gradle, src/main/java/com/bookbla/americano/base/config/AopConfig.java, src/main/java/com/bookbla/americano/base/config/WebConfig.java, src/main/java/com/bookbla/americano/base/filter/ServletWrappingFilter.java, src/main/java/com/bookbla/americano/base/handler/GlobalExceptionHandler.java, src/main/java/com/bookbla/americano/base/log/LogLevel.java, src/main/java/com/bookbla/americano/base/log/RequestStorage.java, src/main/java/com/bookbla/americano/base/log/discord/BookblaDiscord.java, src/main/java/com/bookbla/americano/base/log/discord/DiscordAlarm.java, src/main/java/com/bookbla/americano/base/log/discord/DiscordFeignClient.java, src/main/java/com/bookbla/americano/base/log/discord/DiscordMessage.java, src/main/java/com/bookbla/americano/base/log/discord/ExceptionAppender.java, src/main/java/com/bookbla/americano/base/log/discord/dto/DiscordWebhookMessageRequest.java
> 서비스 내 예외 발생시, 디스코드 채널에 예외를 전송하도록 하였습니다
디스코드 상에는 이런식으로 알림이 오게 됩니다!
>
=> feat: 예외 디스코드 알림 설정

src/main/java/com/bookbla/americano/base/interceptor/AdminInterceptor.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberSchedulerServiceImpl.java
> 어드민 로그인 플로우 변경
as-is : 클라이언트에서 쿠키를 직접 구워야 하는 방식
to-be : 커스텀 헤더 사용
배치성 작업시 디스코드에 로그 발송하도록 추가함
>
=> fix: 어드민 인증 방식 변경

src/main/java/com/bookbla/americano/domain/member/service/impl/MemberBookServiceImpl.java
=> fix: 책 등록시 리뷰 저장 안되는 버그 수정

src/main/java/com/bookbla/americano/domain/postcard/repository/entity/PostcardType.java, src/main/java/com/bookbla/americano/domain/postcard/service/dto/response/PostcardTypeResponse.java
>
- PostCardType 내 imageUrl 추가
- postcard/type-list API 응답에 해당 url 추가
>
=> feat: PostcardType 내 imageUrl 추가

src/main/java/com/bookbla/americano/domain/admin/controller/dto/response/AdminMemberReadResponses.java, src/main/java/com/bookbla/americano/domain/admin/controller/dto/response/AdminPendingMemberResponses.java, src/main/java/com/bookbla/americano/domain/admin/service/AdminMemberService.java, src/main/java/com/bookbla/americano/domain/member/repository/MemberRepository.java, src/test/java/com/bookbla/americano/domain/admin/service/AdminMemberServiceTest.java
> 어드민 내 조회 API 들에 총 개수를 함께 반환하도록 하였습니다
> JPA 쿼리메소드 신기하고 참 좋네요!
=> feat: 어드민 회원 조회 내 회원수 추가

src/main/java/com/bookbla/americano/base/log/discord/DiscordMessage.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberBookCreateRequest.java, src/main/java/com/bookbla/americano/domain/member/enums/MemberStatus.java, src/main/java/com/bookbla/americano/domain/member/exception/MemberBookExceptionType.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/Member.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberBook.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberBookServiceImpl.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberStyleServiceImpl.java, src/test/java/com/bookbla/americano/domain/admin/service/AdminMemberServiceTest.java
>
기존에 함께 관리하던 회원 상태의 도서 등록 + 스타일 등록을
각각 별개의 상태로 보기로 하였습니다
MemberStatus Enum 참고
>
도서 삭제시 2권 이상부터 삭제 가능하도록 설정
=> fix: 도서 등록 필요 상태와 스타일 등록 필요 상태를 분리

src/main/java/com/bookbla/americano/domain/member/repository/MemberBookRepository.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberBook.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberBookServiceImpl.java, src/test/java/com/bookbla/americano/domain/member/service/MemberBookServiceTest.java
=> fix: 회원 도서 soft-delete 적용

src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberResponse.java
> 단일 알파벳에서, enum 문자열 값을 주도록 변경
>
=> refactor: memberStatus 반환값 통일

src/main/java/com/bookbla/americano/domain/auth/service/impl/AuthServiceImpl.java, src/main/java/com/bookbla/americano/domain/member/controller/MemberController.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberStatusUpdateRequest.java, src/main/java/com/bookbla/americano/domain/member/enums/MemberStatus.java, src/main/java/com/bookbla/americano/domain/member/exception/MemberExceptionType.java, src/main/java/com/bookbla/americano/domain/member/repository/MemberStatusLogRepository.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/Member.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberStatusLog.java, src/main/java/com/bookbla/americano/domain/member/service/MemberService.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberBookServiceImpl.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberProfileServiceImpl.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberServiceImpl.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberStyleServiceImpl.java, src/test/java/com/bookbla/americano/domain/member/controller/dto/request/MemberStatusUpdateRequestTest.java, src/test/java/com/bookbla/americano/domain/member/service/MemberServiceTest.java
> 
Member Entity 수정
- 상태 변경 수정 시간 필드 추가
Member Status 수정
- 상태 추가 (MATCHING_DISABLED)
>
=> 멤버 매칭-비활성화 상태 추가

src/main/java/com/bookbla/americano/domain/alarm/exception/PushAlarmExceptionType.java, src/main/java/com/bookbla/americano/domain/alarm/service/impl/AlarmServiceImpl.java, src/main/java/com/bookbla/americano/domain/member/repository/MemberRepository.java
회원 상태가 `COMPLETED`이거나 `MATCHING_DISABLED`일 때만 푸시 알림이 보내지도록 코드 수정
>
>
=> Fix: 회원 상태에 따라 푸시 알림이 보내지도록 수정

src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/MemberPostcardToResponse.java, src/main/java/com/bookbla/americano/domain/postcard/repository/custom/impl/PostcardRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/postcard/service/dto/response/PostcardToResponse.java, src/main/java/com/bookbla/americano/domain/postcard/service/impl/PostcardServiceImpl.java
=> feat: 내 서재 조회 시 책 이미지 URL 반환

src/main/java/com/bookbla/americano/domain/admin/controller/AdminMarketingController.java, src/main/java/com/bookbla/americano/domain/admin/service/AdminMarketingService.java, src/main/java/com/bookbla/americano/domain/notification/infra/expo/ExpoNotificationClient.java, src/main/java/com/bookbla/americano/domain/notification/infra/expo/api/dto/ReceiptsResponse.java, src/main/java/com/bookbla/americano/domain/notification/infra/expo/dto/ExpoNotificationResponse.java
=> fix: 푸쉬알림 결과를 어드민 페이지에 반환하도록 수정

src/main/java/com/bookbla/americano/domain/member/controller/dto/response/BookProfileResponse.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberBookProfileResponse.java, src/main/java/com/bookbla/americano/domain/member/repository/custom/MemberRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberProfileServiceImpl.java
> `all-other-members`호출 시, 이름이 보이지 않던 문제 해결
> - nickname column으로 설정 되어있던 부분을 name으로 return 하게 변경하였습니다.
> - transformMemberName(String name) : 성만 보이고, 나머지 이름은 'O'으로 표기되도록 변환
> 
> `all-other-members`호출 시, 만 나이로 표시되도록 수정
>
=> Fix/home : `all-other-members` 호출 시 이름이 보이지 않는 문제 및 만 나이 문제 수정

src/main/java/com/bookbla/americano/base/config/AuthConfig.java, src/main/java/com/bookbla/americano/domain/setting/controller/SettingController.java, src/main/java/com/bookbla/americano/domain/setting/controller/request/VersionCreateRequest.java, src/main/java/com/bookbla/americano/domain/setting/controller/response/VersionCreateResponse.java, src/main/java/com/bookbla/americano/domain/setting/controller/response/VersionReadResponse.java, src/main/java/com/bookbla/americano/domain/setting/exception/SettingExceptionType.java, src/main/java/com/bookbla/americano/domain/setting/repository/SettingRepository.java, src/main/java/com/bookbla/americano/domain/setting/repository/entity/Setting.java, src/main/java/com/bookbla/americano/domain/setting/service/SettingService.java, src/main/java/com/bookbla/americano/domain/setting/service/impl/SettingServiceImpl.java
=> Feat: 환경 정보 API 구현

src/main/java/com/bookbla/americano/domain/auth/controller/AuthController.java, src/main/java/com/bookbla/americano/domain/member/controller/MemberController.java, src/main/java/com/bookbla/americano/domain/member/controller/MemberEmailController.java, src/main/java/com/bookbla/americano/domain/member/controller/MemberPolicyController.java, src/main/java/com/bookbla/americano/domain/member/controller/MemberProfileController.java, src/main/java/com/bookbla/americano/domain/notification/controller/AlarmController.java, src/main/java/com/bookbla/americano/domain/notification/controller/MemberPushAlarmController.java, src/main/java/com/bookbla/americano/domain/notification/controller/MemberTokenController.java, src/main/java/com/bookbla/americano/domain/quiz/controller/QuizController.java, src/main/java/com/bookbla/americano/domain/setting/controller/SettingController.java
> swagger 문서의 API 상세 설명 추가하였습니다.
>
=> feat: swagger api 설명 작성

src/main/java/com/bookbla/americano/domain/admin/controller/AdminMemberController.java, src/main/java/com/bookbla/americano/domain/admin/service/AdminMemberService.java, src/main/java/com/bookbla/americano/domain/aws/service/S3Service.java, src/main/java/com/bookbla/americano/domain/aws/service/impl/S3ServiceImpl.java, src/test/java/com/bookbla/americano/domain/admin/service/AdminMemberServiceTest.java
> cloudfront 캐시 무효화 내 확장자 추가
프로필 경로 이동하도록 변경
>  이미지 경로 잘 맞는지 확인 필요... 선 머지하겠습니다
=> feat: 프로필 사진 변경 버그 수정

src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberProfile.java, src/main/java/com/bookbla/americano/domain/notification/service/AlarmService.java, src/main/java/com/bookbla/americano/domain/notification/service/impl/AlarmServiceImpl.java, src/main/java/com/bookbla/americano/domain/postcard/enums/PostcardStatus.java, src/main/java/com/bookbla/americano/domain/postcard/service/impl/PostcardServiceImpl.java
상대방 엽서 도착
제목 : 띵동💌 엽서가 도착했어요!
내용 : 김00님이 엽서를 보냈어요! 지금 확인해 보세요🥰
엽서 수락 
제목 : 축하합니다🥳🥳  매칭에 성공하셨습니다~!!💕
내용 : 김00님이 엽서를 수락했어요! 지금 바로 채팅해보세요~🥰
> 위와 같은 형태로 엽서 도착, 매칭 수락할 시에 푸시 알림을 보내도록 구현했습니다.
>
=> Feat: 엽서 도착 및 매칭 수락 푸시 알림 구현

src/main/java/com/bookbla/americano/domain/postcard/repository/PostcardRepository.java, src/main/java/com/bookbla/americano/domain/postcard/service/impl/PostcardServiceImpl.java
> postcard의 엔티티들을 fetch join을 통해 불러오도록 합니다
>
=> fix: 엽서 수락시 fetch join 적용

src/main/java/com/bookbla/americano/domain/postcard/exception/PostcardExceptionType.java, src/main/java/com/bookbla/americano/domain/postcard/repository/entity/Postcard.java, src/test/java/com/bookbla/americano/domain/postcard/repository/entity/PostcardTest.java, src/test/java/com/bookbla/americano/domain/postcard/service/PostcardServiceTest.java
=> fix: 엽서 전송 전, 읽고 답 안하는 경우는 보내지 못하는 검증 추가

src/main/java/com/bookbla/americano/domain/admin/controller/AdminMarketingController.java, src/main/java/com/bookbla/americano/domain/admin/service/AdminMarketingService.java
> 기존 : AlarmClient 사용
변경 : AlarmService 사용
>
=> refactor: 어드민 알림 발송시 AlarmService를 이용하도록 변경

src/main/java/com/bookbla/americano/domain/postcard/service/impl/PostcardServiceImpl.java
=> 받은 엽서 / 보낸 엽서 조회 시 book image url 반환하도록 수

src/main/java/com/bookbla/americano/base/config/SwaggerConfig.java
=> chore: update submodule

.github/workflows/Deploy-prod.yml
> 개발환경 배포시에만 적용되는 부분을 운영환경 배포시에도 적용
>
=> feat: 개발환경과 운영환경의 배포를 동기화한다

src/main/java/com/bookbla/americano/domain/admin/service/AdminMemberService.java, src/main/java/com/bookbla/americano/domain/member/enums/OpenKakaoRoomStatus.java, src/main/java/com/bookbla/americano/domain/member/enums/ProfileImageStatus.java, src/main/java/com/bookbla/americano/domain/member/enums/StudentIdImageStatus.java
=> fix: 어드민 수정

src/main/java/com/bookbla/americano/domain/member/service/dto/MemberProfileDto.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberProfileServiceImpl.java
=> Fix: MemberStatus 바로 스타일 입력으로 변경

src/main/java/com/bookbla/americano/domain/library/controller/MemberLibraryController.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberProfileServiceImpl.java
> 임시로 어드민에서 바꾸지 않고, 바로 변경되도록 반영합니다
>
=> fix: 서재 내 사진 변경과 오픈카톡방 변경도 그대로 반영하도록 수정

src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberReportCreateRequest.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberReportCreateResponse.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberReportReadResponse.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberReport.java, src/main/java/com/bookbla/americano/domain/member/service/impl/MemberReportServiceImpl.java
=> Fix: Boolean etcReport 컬럼 삭제

.github/workflows/Deploy-prod.yml
> master 브랜치에서 main으로 변경합니다!
>
=> feat: 브랜치 이름 master -> main 변경

src/main/java/com/bookbla/americano/domain/library/controller/dto/MemberLibraryProfileReadResponse.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberBookProfileResponse.java, src/main/java/com/bookbla/americano/domain/notification/service/AlarmService.java, src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/MemberPostcardFromResponse.java, src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/MemberPostcardToResponse.java
> 이름을 마스킹처리해서 보내는 부분들을 제거합니다
홈 - 책제목과 학교 사이
상대페이지 - 이름
보낸 엽서 - 이름(대기중, 거절, 독서퀴즈 틀릴 때)
받은 엽서 - 열어볼 때
알림 - 엽서 도착 시
>
=> fix: 이름 마스킹 제거

src/main/java/com/bookbla/americano/base/config/AuthConfig.java, src/main/java/com/bookbla/americano/domain/member/controller/MemberEmailController.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberEmailSendRequest.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberEmailVerifyRequest.java, src/main/java/com/bookbla/americano/domain/member/exception/MemberEmailExceptionType.java, src/main/java/com/bookbla/americano/domain/member/service/MemberEmailService.java, src/main/java/com/bookbla/americano/domain/school/controller/SchoolController.java, src/main/java/com/bookbla/americano/domain/school/controller/dto/response/SchoolReadResponse.java, src/main/java/com/bookbla/americano/domain/school/exception/SchoolExceptionType.java, src/main/java/com/bookbla/americano/domain/school/repository/SchoolRepository.java, src/main/java/com/bookbla/americano/domain/school/service/SchoolService.java
=> feat: MemberEmail에 학교 이름과 도메인 URL 검증 로직 추가

src/main/java/com/bookbla/americano/domain/member/service/MemberProfileService.java, src/main/java/com/bookbla/americano/domain/member/service/dto/MemberProfileDto.java
=> fix: 관리자 인증 적용

src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/MemberPostcardFromResponse.java, src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/MemberPostcardToResponse.java, src/main/java/com/bookbla/americano/domain/postcard/repository/custom/impl/PostcardRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java, src/main/java/com/bookbla/americano/domain/postcard/service/dto/response/PostcardToResponse.java
> 받은 엽서(MemberPostcardToResponse)에 키 정보 추가하였습니다. 
> MemberPostcardToResponse, MemberPostcardFromResponse 생성자도 수정(리팩토링...?)하였습니다.
>
=> fix: 받은 엽서에 상대방 키 정보 추가 및 보낸엽서, 받은 엽서 Response DTO 생성자 수정

src/main/java/com/bookbla/americano/domain/admin/event/AdminNotificationEventListener.java, src/main/java/com/bookbla/americano/domain/auth/service/AuthService.java, src/main/java/com/bookbla/americano/domain/auth/service/dto/event/AdminNotificationEventWithoutTransaction.java, src/main/java/com/bookbla/americano/domain/member/service/MemberProfileService.java, src/main/java/com/bookbla/americano/domain/member/service/MemberReportService.java, src/main/java/com/bookbla/americano/domain/member/service/dto/event/AdminNotificationEventWithAfterCommit.java
> 신규 회원 가입시 알림을 발송하도록 설정하였습니다
>
=> feat: 신규 회원 가입시 알림 발송

src/main/java/com/bookbla/americano/domain/admin/service/AdminVerificationService.java, src/main/java/com/bookbla/americano/domain/notification/enums/PushAlarmForm.java, src/main/java/com/bookbla/americano/domain/notification/service/AlarmService.java
=> feat: 회원 승인 푸시알림 구현

src/main/java/com/bookbla/americano/domain/member/repository/entity/Member.java, src/main/java/com/bookbla/americano/domain/notification/controller/MemberPushAlarmController.java, src/main/java/com/bookbla/americano/domain/notification/controller/dto/request/PushAlarmSettingCreateRequest.java, src/main/java/com/bookbla/americano/domain/notification/controller/dto/response/PushAlarmSettingResponse.java, src/main/java/com/bookbla/americano/domain/notification/service/AlarmService.java, src/main/java/com/bookbla/americano/domain/notification/service/MemberPushAlarmService.java
1. Member 테이블에 `pushTokenEnabled` 추가 (on/off 기능)
2, /members/push-alarms/settings  REST API 추가
>
>
=> Feat: 푸시 알림 on/off 설정 구현

src/main/java/com/bookbla/americano/domain/notification/service/AlarmService.java, src/test/java/com/bookbla/americano/domain/admin/service/AdminVerificationServiceTest.java
=> fix: 예외처리 삭제

src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/MemberPostcardToResponse.java, src/main/java/com/bookbla/americano/domain/postcard/repository/custom/impl/PostcardRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java, src/main/java/com/bookbla/americano/domain/postcard/service/dto/response/PostcardToResponse.java
> 받은 엽서(/postcard/to) 조회 시, 가장 최근에 받은 엽서 순서로 정렬되도록 수정하였습니다.
>
=> fix : 받은 엽서 정렬 - 가장 최근에 받은 순서대로 출력되도록 수정

src/main/java/com/bookbla/americano/domain/admin/service/AdminMarketingService.java, src/main/java/com/bookbla/americano/domain/member/controller/MemberController.java, src/main/java/com/bookbla/americano/domain/member/controller/MemberEmailController.java, src/main/java/com/bookbla/americano/domain/member/controller/MemberPolicyController.java, src/main/java/com/bookbla/americano/domain/member/controller/MemberProfileController.java, src/main/java/com/bookbla/americano/domain/member/repository/MemberRepository.java, src/main/java/com/bookbla/americano/domain/notification/controller/MemberTokenController.java, src/main/java/com/bookbla/americano/domain/notification/service/AlarmService.java, src/main/java/com/bookbla/americano/domain/setting/controller/SettingController.java
1. 광고 알림을 광고 동의가 있을 때 알림이 가도록 수정
2. Swagger API 문서화
>
>
=> Fix: 광고 동의(adAgrementPolicy)에 맞게 알림이 가도록 기능 수정

.github/workflows/Deploy-dev.yml, .github/workflows/Deploy-prod.yml
> 기존 성공시에만 알림 보내던 것을
성공/실패 유무, PR, 브랜치 정보를 함께 반환하도록 하였슴니당
>
=> chore: 배포 성공/실패 결과 정보 추가

src/main/java/com/bookbla/americano/domain/book/infra/aladin/AladinBookClient.java, src/main/java/com/bookbla/americano/domain/book/infra/aladin/dto/AladinBookResponse.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberBookCreateRequest.java, src/main/java/com/bookbla/americano/domain/member/service/MemberBookService.java
> 알라딘 도서 없을 시 카카오 도서 검색에서의 기본 이미지를 사용하도록 변경
>
=> fix: 기본 이미지 설정값 추가

src/main/java/com/bookbla/americano/domain/admin/service/AdminVerificationService.java, src/main/java/com/bookbla/americano/domain/member/enums/MemberStatus.java, src/main/java/com/bookbla/americano/domain/member/service/MemberBookService.java, src/main/java/com/bookbla/americano/domain/member/service/MemberProfileService.java
=> fix: 학생증 인증이 필요한 상태, 'APPROVAL'로 변경

src/main/java/com/bookbla/americano/domain/member/repository/MemberPushAlarmRepository.java, src/main/java/com/bookbla/americano/domain/notification/service/MemberPushAlarmService.java
=> fix: 푸쉬 알림 내림차순으로 수정

src/main/java/com/bookbla/americano/domain/admin/service/AdminVerificationService.java, src/main/java/com/bookbla/americano/domain/member/enums/MemberStatus.java, src/main/java/com/bookbla/americano/domain/member/service/MemberProfileService.java
=> fix: 학생증 인증 거절 구현

src/main/java/com/bookbla/americano/view/library/controller/dto/MyLibraryReadResponse.java
=> 내서재/상대방서재 정보 응답 smokeType 내용 수정

src/main/java/com/bookbla/americano/domain/member/enums/SmokeType.java, src/main/java/com/bookbla/americano/view/library/controller/dto/MyLibraryReadResponse.java
=> 내서재/상대방서재 정보 응답 smokeType 내용 수정 #2

src/main/java/com/bookbla/americano/base/config/AuthConfig.java, src/main/java/com/bookbla/americano/base/config/WebSocketConfig.java, src/main/java/com/bookbla/americano/domain/chat/controller/ChatController.java, src/main/java/com/bookbla/americano/domain/chat/controller/dto/ChatDto.java, src/main/java/com/bookbla/americano/domain/chat/repository/MemberChatRoomRepository.java, src/main/java/com/bookbla/americano/domain/chat/repository/custom/MemberChatRoomRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/chat/repository/custom/impl/ChatRoomRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/chat/repository/custom/impl/MemberChatRoomRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/chat/repository/entity/Chat.java, src/main/java/com/bookbla/americano/domain/chat/repository/entity/ChatRoom.java, src/main/java/com/bookbla/americano/domain/chat/service/ChatWebSocketHandler.java, src/main/java/com/bookbla/americano/domain/chat/service/impl/ChatRoomServiceImpl.java, src/main/java/com/bookbla/americano/domain/member/repository/custom/MemberRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/notification/service/AlarmService.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java
=> feat: Add WebSocket configuration and ChatController

src/main/java/com/bookbla/americano/domain/chat/controller/dto/ChatRoomResponse.java, src/main/java/com/bookbla/americano/domain/chat/repository/custom/ChatRoomRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/chat/repository/custom/impl/ChatRoomRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/chat/repository/entity/MemberChatRoom.java
=> feat: Add unread count to MemberChatRoom entity

src/main/java/com/bookbla/americano/base/config/WebSocketConfig.java, src/main/java/com/bookbla/americano/domain/chat/controller/dto/ChatRoomResponse.java, src/main/java/com/bookbla/americano/domain/chat/repository/custom/ChatRoomRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/chat/repository/custom/impl/ChatRoomRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/chat/repository/entity/MemberChatRoom.java
=> feat: Add unread count field to MemberChatRoom entity

src/main/java/com/bookbla/americano/domain/payment/infrastructure/apple/AppleTokenProvider.java
=> fix: 애플 요청에 보내는 토큰 타입 값 수정

src/main/java/com/bookbla/americano/domain/member/service/MemberProfileService.java
=> hotfix: 학생증 이미지 상태 반영이 안되는 버그 수정

src/main/java/com/bookbla/americano/domain/payment/infrastructure/apple/AppleLibraryProvider.java, src/main/java/com/bookbla/americano/domain/payment/infrastructure/apple/ApplePaymentStrategy.java, src/main/java/com/bookbla/americano/domain/payment/infrastructure/apple/AppleTokenProvider.java, src/main/java/com/bookbla/americano/domain/payment/infrastructure/apple/tokens/DecodedTokenPayload.java
>  응답값이 바뀌는건가 싶지만..
일단 맞춰서 바꿔놨습니다
>
=> fix: 인앱결제 토큰 페이로드 수정

src/main/java/com/bookbla/americano/domain/member/controller/MemberReportController.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberReportCreateRequest.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberReportCreateResponse.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberReportReadResponse.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberReport.java, src/main/java/com/bookbla/americano/domain/member/service/MemberReportService.java
>신고하기 항목
: 독서 퀴즈, 한 줄 감상문, 개인 질문,  개인 질문 답변, 프로필 -> 사진닉네임, 독서 퀴즈,  한 줄 감상문, 불쾌함을 주는 대화, 부적절한 만남 추구, 기타
>
=> feat: 신고하기 항목 수정

src/main/java/com/bookbla/americano/domain/member/controller/MemberController.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberOnboardingStatusResponse.java, src/main/java/com/bookbla/americano/domain/member/service/MemberService.java, src/test/java/com/bookbla/americano/domain/member/service/MemberServiceTest.java
> 프론트에서 사용자의 온모딩 모달 상태 정보를 조회할 수 있는 API를 추가했습니다
=> Feat: 사용자 온모딩 모달 상태 업데이트 기능 추가

src/main/java/com/bookbla/americano/domain/member/controller/MemberMatchController.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberIntroResponse.java
=> fix: 매칭 컨트롤러 API 파라미터 수정

src/main/java/com/bookbla/americano/domain/chat/controller/dto/ChatRoomResponse.java
=> fix: conflict error

src/main/java/com/bookbla/americano/domain/chat/repository/custom/MemberChatRoomRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/chat/repository/custom/impl/ChatRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/chat/repository/custom/impl/MemberChatRoomRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/chat/repository/entity/MemberChatRoom.java, src/main/java/com/bookbla/americano/domain/chat/service/impl/ChatRoomServiceImpl.java, src/main/java/com/bookbla/americano/domain/chat/service/impl/ChatServiceImpl.java, src/main/java/com/bookbla/americano/domain/notification/service/AlarmService.java
=> fix: chat websocket

src/main/java/com/bookbla/americano/domain/member/service/MemberBookService.java
> BOOK -> APPROVAL은 회원 상태 업데이트 API를 통해 반영합니다
>
=> fix: 책 등록시 memberStatus 업데이트 제거

src/main/java/com/bookbla/americano/domain/member/service/MemberProfileService.java
=> fix: MemberVerify description이 생성이 안되는 버그 수정

src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberRepositoryCustomImpl.java
=> fix: memberRepository.findByChatRoomId error fix

src/main/java/com/bookbla/americano/domain/chat/service/impl/ChatServiceImpl.java, src/main/java/com/bookbla/americano/domain/notification/controller/InAppAlarmController.java, src/main/java/com/bookbla/americano/domain/notification/controller/dto/request/InAppAlarmRequest.java, src/main/java/com/bookbla/americano/domain/notification/repository/entity/InAppAlarmLog.java, src/main/java/com/bookbla/americano/domain/notification/service/InAppAlarmService.java
=> fix: list chat sort by chat.sendtime desc

src/main/java/com/bookbla/americano/domain/chat/controller/dto/ChatRoomResponse.java, src/main/java/com/bookbla/americano/domain/chat/repository/custom/impl/ChatRoomRepositoryCustomImpl.java
=> fix: add postcard sender id in list chat room api

src/main/java/com/bookbla/americano/domain/chat/repository/custom/impl/ChatRoomRepositoryCustomImpl.java
=> fix: unreadcount fix in list chat room api

src/main/java/com/bookbla/americano/domain/auth/service/AuthService.java, src/main/java/com/bookbla/americano/domain/member/controller/MemberController.java, src/main/java/com/bookbla/americano/domain/member/controller/MemberProfileController.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberNameVerifyRequest.java, src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberNameVerifyResponse.java, src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/Member.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberProfile.java, src/main/java/com/bookbla/americano/domain/member/service/MemberMatchingService.java, src/main/java/com/bookbla/americano/domain/member/service/MemberProfileService.java, src/main/java/com/bookbla/americano/domain/member/service/dto/MemberRecommendationDto.java, src/main/java/com/bookbla/americano/domain/postcard/repository/entity/Postcard.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java, src/test/java/com/bookbla/americano/domain/member/service/MemberProfileServiceTest.java
> 기존에 있던 기능 따로 안 건들고 있던 기능들만 사용해서 api 분리했습니다
북블라, 비속어 등 검증하는 테스트 코드 또한 작성하였습니다
=> feat: 사용자 닉네임 검증 API 구현

src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberRepositoryCustomImpl.java
> 프론트 단에서 테스트를 위해 임시로 수정했습니다
>
=> fix: 최소한의 조건만 걸도록 변경

src/main/java/com/bookbla/americano/domain/payment/infrastructure/google/GoogleCertificationProvider.java
=> chore: 구글 결제 에러 로그 추가

.github/workflows/Deploy-dev.yml, .github/workflows/Deploy-prod.yml
=> chore: json 파일 저장 위치 확인

src/main/java/com/bookbla/americano/domain/payment/infrastructure/google/config/GooglePaymentConfig.java
=> fix: ClassPathResource를 사용하여 파일 위치 명시

src/main/java/com/bookbla/americano/domain/payment/infrastructure/google/api/dto/response/GooglePaymentPurchaseResponse.java
=> fix: DTO Response에러 발생 값 삭제

src/main/java/com/bookbla/americano/domain/member/repository/entity/Member.java
=> hotfix: change primitive type to wrapper class

src/main/java/com/bookbla/americano/base/config/RedisConfig.java, src/main/java/com/bookbla/americano/domain/chat/controller/dto/ChatPubMessage.java, src/main/java/com/bookbla/americano/domain/chat/controller/dto/ChatSubMessage.java, src/main/java/com/bookbla/americano/domain/chat/repository/ChatRoomRedisRepository.java, src/main/java/com/bookbla/americano/domain/chat/repository/redis/ChatRoomRedisRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/chat/service/RedisPublisher.java, src/main/java/com/bookbla/americano/domain/chat/service/RedisSubscriber.java, src/main/java/com/bookbla/americano/domain/chat/service/impl/ChatServiceImpl.java
=> fix: put chat id in list chat api

src/main/java/com/bookbla/americano/domain/chat/controller/dto/ChatDto.java
=> fix: add chat id in list chat api

src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberIntroResponse.java, src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberRepositoryCustomImpl.java
=> fix: 홈 화면 api query 수정

src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberRepositoryCustomImpl.java
=> fix: 홈 화면 API LocalDateTime 변경

src/main/java/com/bookbla/americano/domain/member/controller/MemberMatchingController.java, src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/member/service/MemberMatchingService.java
=> fix: 매칭 API BookId -> MemberBookId 수정

src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberRepositoryCustomImpl.java
=> fix: 매칭 API 쿼리 수정

src/main/java/com/bookbla/americano/domain/member/repository/MemberMatchRepository.java, src/main/java/com/bookbla/americano/domain/member/service/MemberMatchingService.java
=> fix: 매칭 API native query로 변경

src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberModal.java, src/main/java/com/bookbla/americano/domain/school/repository/entity/Invitation.java, src/main/java/com/bookbla/americano/domain/school/repository/entity/InvitationStatus.java
=> fix: 친구 초대 보상 API NONE 컬럼 추가

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingFilter.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java, src/main/java/com/bookbla/americano/domain/member/repository/MemberVerifyRepository.java, src/main/java/com/bookbla/americano/domain/member/repository/custom/MemberVerifyRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberVerifyRepositoryCustomImpl.java
=> fix: 홈 화면 API 랜덤 기능 추가

src/main/java/com/bookbla/americano/domain/member/exception/MemberBookExceptionType.java, src/main/java/com/bookbla/americano/domain/member/repository/MemberVerifyRepository.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/Member.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberVerify.java, src/main/java/com/bookbla/americano/domain/member/service/MemberService.java, src/test/java/com/bookbla/americano/domain/school/service/InvitationServiceTest.java
=> fix: memberStatus 변경시 학생증 미인증 방어로직 추가

src/main/java/com/bookbla/americano/domain/member/service/MemberService.java
=> hotfix: 커밋 누락 추가

src/main/java/com/bookbla/americano/domain/chat/service/impl/ChatServiceImpl.java
=> fix: fixed chat unread

src/main/java/com/bookbla/americano/domain/chat/repository/custom/impl/ChatRoomRepositoryCustomImpl.java
=> fix: 엽서 수락하지 않을 시 채팅방 생성되지 않게

src/main/java/com/bookbla/americano/base/config/WebConfig.java, src/main/java/com/bookbla/americano/base/log/query/ConnectionProxyHandler.java, src/main/java/com/bookbla/americano/base/log/query/LoggingInterceptor.java, src/main/java/com/bookbla/americano/base/log/query/QueryCounter.java, src/main/java/com/bookbla/americano/base/log/query/QueryCounterAop.java
>  최근에 요청 한번당 쿼리가 좀 많이 찍히는 것 같아서, 쿼리 개수를 세는 카운터를 적용하려고 합니다
>
=> feat: 쿼리 카운터 적용

src/main/java/com/bookbla/americano/domain/chat/controller/ChatRoomController.java, src/main/java/com/bookbla/americano/domain/chat/controller/dto/ChatRoomResponse.java, src/main/java/com/bookbla/americano/domain/chat/repository/custom/ChatRoomRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/chat/repository/custom/impl/ChatRoomRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/chat/service/ChatRoomService.java, src/main/java/com/bookbla/americano/domain/chat/service/impl/ChatRoomServiceImpl.java, src/main/java/com/bookbla/americano/domain/chat/service/impl/ChatServiceImpl.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberBookmark.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java
=> feat: get chat room related to postcard

src/main/java/com/bookbla/americano/domain/member/exception/MemberBookmarkExceptionType.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/Member.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberBookmark.java, src/main/java/com/bookbla/americano/domain/member/service/MemberBookService.java, src/main/java/com/bookbla/americano/domain/member/service/MemberService.java
>
기존 : 가입과정에서 등록하는 책에 대해서만 책갈피를 지급
변경 : 최초 등록하는 4권까지만 책갈피를 지급
>
=> fix: 책 등록시 재화 보상 로직 수정

src/main/java/com/bookbla/americano/domain/payment/infrastructure/google/GooglePaymentStrategy.java
=> fix: purchaseId 로그 확인

src/main/java/com/bookbla/americano/domain/payment/infrastructure/google/GooglePaymentStrategy.java
=> fix: PaymentInformation 전체 로그 확인

.github/workflows/Deploy-dev.yml, .github/workflows/Deploy-prod.yml
=> hotfix : update action-*-artifact version from v1 to v4

.github/workflows/Deploy-dev.yml, .github/workflows/Deploy-prod.yml, Dockerfile-dev, Dockerfile-prod
=> fix: update dockerfile jarfile path

.github/workflows/Deploy-dev.yml, .github/workflows/Deploy-prod.yml
=> fix: artifact path 정의

src/main/java/com/bookbla/americano/domain/postcard/repository/custom/impl/PostcardRepositoryCustomImpl.java
=> fix: 엽서 거절시 필터링 쿼리 수정

src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberBookmark.java, src/main/java/com/bookbla/americano/domain/member/service/MemberBookService.java
> 10개 -> 2개
> 함수명 이상한 것들도 추가로 바꿨슴니다
=> fix: 애드몹 시청시 책갈피 보상 개수 변경

src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberVerifyRepositoryCustomImpl.java
=> fix: 햑생증 인증 필터링 쿼리 수정

src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberVerifyRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/postcard/repository/custom/impl/PostcardRepositoryCustomImpl.java
=> fix: 햑생증 인증 + 엽서 거절 필터링 쿼리 직관적으로 수정

src/main/java/com/bookbla/americano/domain/member/repository/MemberPushAlarmRepository.java, src/main/java/com/bookbla/americano/domain/notification/controller/MemberPushAlarmController.java, src/main/java/com/bookbla/americano/domain/notification/controller/dto/response/MemberPushAlarmReadResponses.java, src/main/java/com/bookbla/americano/domain/notification/controller/dto/response/MemberPushAlarmResponse.java, src/main/java/com/bookbla/americano/domain/notification/service/MemberPushAlarmService.java
=> fix: push alarm 페이징 처리 구현

src/main/java/com/bookbla/americano/domain/notification/controller/MemberPushAlarmController.java
=> fix: MemberPushAlarm 컨트롤러 api 수정

src/main/java/com/bookbla/americano/domain/matching/controller/MemberMatchingController.java, src/main/java/com/bookbla/americano/domain/matching/controller/dto/response/MemberIntroResponse.java, src/main/java/com/bookbla/americano/domain/matching/repository/entity/MemberMatching.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java, src/main/java/com/bookbla/americano/domain/quiz/controller/QuizController.java, src/main/java/com/bookbla/americano/domain/quiz/controller/dto/request/QuizQuestionVerifyRequest.java, src/main/java/com/bookbla/americano/domain/quiz/controller/dto/response/QuizQuestionVerifyResponse.java, src/main/java/com/bookbla/americano/domain/quiz/service/QuizQuestionService.java
> 독서 퀴즈를 검증하는 부분에서 틀렸을 때 **독서퀴즈 출제자**의 홈에서 보이지 않도록 조건을 추가했습니다
>
=> feat: 독서 퀴즈 틀렸을 때 매칭 제외조건에 추가

.github/workflows/Deploy-dev.yml, .github/workflows/Deploy-prod.yml
=> chore: ci 실패 알림 추가

src/main/java/com/bookbla/americano/domain/book/repository/entity/Book.java, src/main/java/com/bookbla/americano/domain/matching/controller/MemberMatchingController.java, src/main/java/com/bookbla/americano/domain/matching/controller/dto/request/RejectMemberRequest.java, src/main/java/com/bookbla/americano/domain/matching/exception/MemberMatchingExceptionType.java, src/main/java/com/bookbla/americano/domain/matching/repository/custom/MemberMatchingRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MemberMatchingRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/matching/repository/entity/MatchedInfo.java, src/main/java/com/bookbla/americano/domain/matching/repository/entity/MemberMatching.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingFilter.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java, src/main/java/com/bookbla/americano/domain/member/repository/MemberBlockRepository.java, src/main/java/com/bookbla/americano/domain/member/repository/custom/MemberBlockRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberBlockRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/postcard/repository/custom/impl/PostcardRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/school/repository/entity/School.java, src/test/java/com/bookbla/americano/domain/school/service/InvitationServiceTest.java
> 기존 ElementCollection으로 구분한 컬럼에서 MatchedInfo로 분리했습니다
알고리즘을 가중치를 통해 구현해보았습니다
> 리뷰 부탁드립니다..!
=> feat: 소개 알고리즘 구현

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java
=> fix: matching api 호출 시 저자 확인 과정에서 NPE 오류 해결

src/main/java/com/bookbla/americano/domain/matching/controller/MemberMatchingController.java
=> fix: 매칭 회원 거절 API 수정

src/main/java/com/bookbla/americano/domain/matching/controller/MemberMatchingController.java, src/main/java/com/bookbla/americano/domain/matching/controller/dto/request/RefreshMemberRequest.java, src/main/java/com/bookbla/americano/domain/matching/controller/dto/request/RejectMemberRequest.java, src/main/java/com/bookbla/americano/domain/matching/repository/entity/MemberMatching.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingFilter.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java, src/main/java/com/bookbla/americano/domain/school/repository/entity/School.java
> 다른 사용자 추천받기, 소개 거절 API 분리했습니다
=> fix: 회원 소개 새로고침, 거절 API 분리

src/main/java/com/bookbla/americano/domain/school/repository/entity/Invitation.java, src/main/java/com/bookbla/americano/domain/school/repository/entity/InvitationType.java, src/main/java/com/bookbla/americano/domain/school/service/InvitationService.java, src/test/java/com/bookbla/americano/domain/school/service/InvitationServiceTest.java
=> fix: Gender 성별과 InvitationType 성별 통일

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingFilter.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberModal.java
> CollectionTable 사용 시 예상하지 못한 테이블이 생성되어 잠시 수정합니다
>
=> fix: Member 모달 테이블 변경

src/main/java/com/bookbla/americano/domain/matching/controller/MemberMatchingController.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 매칭 회원 새로고침 반환되도록 수정

src/main/java/com/bookbla/americano/domain/matching/exception/MemberMatchingExceptionType.java, src/main/java/com/bookbla/americano/domain/matching/repository/MatchedInfoRepository.java, src/main/java/com/bookbla/americano/domain/matching/repository/entity/MemberMatching.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberModal.java
> matchedInfoRepository를 통해 찾아와서 바로 반환하도록 변경했습니다
>
=> fix: 필터링된 매칭 회원이 반한되지 않는 문제 해결

src/main/java/com/bookbla/americano/domain/matching/repository/entity/MemberMatching.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 매칭 무시 초기화 문제 해결

src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchedInfoRepositoryImpl.java
=> fix: matched_info query 수정

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 매칭회원 조회, 갱신 로직 수정

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 매칭 갱신 오류 코드 수정

src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MemberMatchingRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/matching/repository/entity/MatchedInfo.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> MatchingRepository query 수정

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java, src/main/java/com/bookbla/americano/domain/matching/service/dto/MatchingSimilarityWeightConstants.java
> 추후 확장성을 위해 매칭 알고리즘 가중치를 별도 상수로 빼두었습니다
for문을 통해 쿼리를 계속 날리기보단 한번에 모든 쿼리를 보낸 뒤 조회하는 방식으로 최적화했습니다
>
=> fix: 매칭 알고리즘 최적화

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java
=> fix: isSameBook NPE 문제 해결

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java
=> fix: 매칭 알고리즘 NPE 문제 해결

src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MemberMatchingRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/matching/repository/entity/MatchedInfo.java, src/main/java/com/bookbla/americano/domain/matching/repository/entity/MemberMatching.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: MatchedInfo, MemberMatching 양방향 저장 문제 해결

src/main/java/com/bookbla/americano/domain/matching/repository/custom/MatchedInfoRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchedInfoRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> feat: 필터링된 matchedInfo 저장, 업데이트 쿼리 배치 처리

src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchedInfoRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
> Entity Manager -> JdbcTemplate.updateBatch 로 수정했습니다
>
=> fix: batch insert 문제 해결

src/main/java/com/bookbla/americano/domain/matching/repository/MatchedInfoRepository.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: refresh 시 다른 사용자를 반환하는 문제 해결

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java
=> fix: 가중치가 저장되지 않는 문제 해결

src/main/java/com/bookbla/americano/domain/matching/repository/custom/MatchedInfoRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchedInfoRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 상태 변경이 일어났을 때 디비에 바로 수정되도록 변경

src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchedInfoRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/postcard/controller/PostcardController.java, src/main/java/com/bookbla/americano/domain/postcard/controller/dto/request/PostcardStatusUpdateRequest.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java
=> fix: 엽서 거절 시, 내 홈 화면에 엽서를 거절한 사람의 그 책이 뜨지 않도록 변경

src/main/java/com/bookbla/americano/domain/member/repository/entity/Member.java
> 프론트 요청으로 newPersonAdmobCount 2 -> 3 개로 변경했습니다
>
=> fix: newPersonAdmobCount 개수 변경

src/main/java/com/bookbla/americano/domain/member/service/MemberReportService.java
=> feat: 신고시 매칭에서 제외되도록 excluded 에 추가

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
> 쿼리 최적화를 위해 MatchingAlgorithmFilter에서 저자를 한번에 긁어오도록 수정했습니다
matched_info에 가중치가 null 값이 되던 오류를 수정했습니다
>
=> refactor: Authors query batch 처리, save 로직 수정

src/main/java/com/bookbla/americano/domain/matching/controller/dto/response/MemberIntroResponse.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 매칭될 사용자가 없을 때 null로 처리해서 보내줌

src/main/java/com/bookbla/americano/domain/postcard/repository/entity/Postcard.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java, src/main/java/com/bookbla/americano/domain/postcard/service/dto/request/SendPostcardRequest.java, src/test/java/com/bookbla/americano/domain/postcard/service/PostcardServiceTest.java
> 엽서보낼때 memberBookId 추가
> Q. Postcard 엔티티에 receiveMemberBookId를 추가해서 같이 관리해야할까요?!
=> fix: SendPostcardRequest에 memberBookId 추가

src/main/java/com/bookbla/americano/domain/matching/controller/dto/response/MemberIntroResponse.java, src/main/java/com/bookbla/americano/domain/matching/repository/MatchExcludedRepository.java, src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MemberMatchingRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java
=> fix: 매칭 사용자가 없을 때 빈 객체를 반환하도록 변경

src/main/java/com/bookbla/americano/domain/matching/repository/MatchedInfoRepository.java, src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchedInfoRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/matching/repository/entity/MemberMatching.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 사용자 매칭 NPE 문제 해결

src/main/java/com/bookbla/americano/domain/matching/controller/MemberMatchingController.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: refresh 로직 수정

src/main/java/com/bookbla/americano/domain/book/repository/entity/Book.java, src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MemberMatchingRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/matching/repository/entity/MatchedInfo.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java, src/main/java/com/bookbla/americano/domain/matching/service/dto/MemberRecommendationDto.java
=> fix: 추천 필터링 save 쿼리 수정, 로깅 추가

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java, src/main/java/com/bookbla/americano/domain/member/repository/MemberBookRepository.java, src/main/java/com/bookbla/americano/domain/member/repository/custom/MemberBookRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberBookRepositoryImpl.java
=> fix: MemberBook fetch join 으로 가져오도록 변경

src/main/java/com/bookbla/americano/domain/member/repository/MemberRepository.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/Member.java, src/main/java/com/bookbla/americano/scheduler/ScheduleWorker.java
> 바뀐 기획상 newPersonAdmob 수를 3-> 4로 변경하였고 이제 newPerson 의미로 사용되어 변수명을 수정하고싶었으나 생각보다 대공사인 부분이라 일단 exception만 수정합니다ㅜ
>
=>  fix: 새로운 사람 만나기 횟수 3 -> 4로 변경

src/main/java/com/bookbla/americano/domain/admin/service/AdminAuthService.java, src/main/java/com/bookbla/americano/domain/admin/service/AdminVerificationService.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberBookmark.java, src/test/java/com/bookbla/americano/domain/admin/service/AdminVerificationServiceTest.java
=> feat: 학생증 인증 성공시 재화 지급 추가

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 데이터가 중복되어 저장되는 문제 해결

src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MemberMatchingRepositoryImpl.java
=> fix: 매칭 쿼리 수정

src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MemberMatchingRepositoryImpl.java
=> fix: 홈 매칭 쿼리 수정(일단 members-match만)

src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchedInfoRepositoryImpl.java
=> fix: 매칭 쿼리 수정(/members-match/refresh)

src/main/java/com/bookbla/americano/domain/matching/controller/dto/response/MemberIntroResponse.java, src/main/java/com/bookbla/americano/domain/matching/repository/MemberMatchingRepository.java, src/main/java/com/bookbla/americano/domain/matching/repository/entity/MemberMatching.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java, src/main/java/com/bookbla/americano/domain/member/service/MemberReportService.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java, src/main/java/com/bookbla/americano/domain/quiz/service/QuizQuestionService.java, src/main/java/com/bookbla/americano/scheduler/ScheduleWorker.java, src/test/java/com/bookbla/americano/domain/postcard/service/PostcardServiceTest.java
> 앱 접속시 처음에
>
> 초대카드가 뜨는 경우 (isInvitationCard = true)
> - 최초 가입했을 때
> - 자정이 되었을 때 
> - 엽서 보냈을 때
> - 독서퀴즈 틀렸을 때 
> - 상대방을 신고했을 때 
>  
> 소개카드가 뜨는 경우 (isInvitationCard = false)
> - 소개카드를 본 이후(= 새로고침 이후) 엽서를 안보내는 등 행동 없이 앱 재시작했을 때
> - 앱 내 다른 페이지 이동 했다가 다시 홈 왔을 때
>
=> feat: 상황별 isInvitationCard 처리

src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MemberMatchingRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 매칭 알고리즘 쿼리 수정 및 학생증 인증 필터링 제거

src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MemberMatchingRepositoryImpl.java
> 특정 회원의 특정 책을 삭제했을때 특정 회원의 다른 책은 나와야하는데 특정 회원이 아예 안나오는 문제 해결
>
=> fix: 매칭 알고리즘 쿼리 수정

src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MemberMatchingRepositoryImpl.java
> matchExcludedInfo는 따로 빼거나 다시 필터링하겠습니다. matchExcludedInfo관련 코드때매 /api/members-match 에러나는 관계로 일단 머지하겠습니다ㅠ
>
=> fix: matchExcludedInfo 관련 코드 삭제

src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MemberMatchingRepositoryImpl.java
=> fix: 최소조건 매칭 쿼리 수정

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 엽서 보낸 후 isInvitationCard가 true로 바뀌지 않는 문제 해결

src/main/java/com/bookbla/americano/domain/matching/repository/MatchExcludedRepository.java, src/main/java/com/bookbla/americano/domain/matching/repository/custom/MatchExcludedRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchExcludedRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MemberMatchingRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingFilter.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
> 최소조건에서 같이 처리하려다보니까 문제가 좀 있네용,,
>
=> fix: 최소 조건에서 excluded 필터링 나눠서 구현

src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchedInfoRepositoryImpl.java
=> fix: refresh 된 책이 아닌 회원이 안나오는 문제 해결

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java, src/main/java/com/bookbla/americano/domain/member/repository/MemberBookRepository.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberBook.java
=> fix: 책과 저자를 가져오는 쿼리 최적화

src/main/java/com/bookbla/americano/domain/postcard/controller/PostcardController.java, src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/PostcardReadResponse.java, src/main/java/com/bookbla/americano/domain/postcard/repository/entity/Postcard.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java, src/main/java/com/bookbla/americano/domain/postcard/service/dto/request/SendPostcardRequest.java, src/test/java/com/bookbla/americano/domain/postcard/service/PostcardServiceTest.java
=> feat: Postcard에 channelUrl 추가

src/main/java/com/bookbla/americano/domain/matching/controller/MemberMatchingController.java, src/main/java/com/bookbla/americano/domain/matching/repository/MatchedInfoRepository.java, src/main/java/com/bookbla/americano/domain/matching/repository/custom/MatchIgnoredRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/matching/repository/custom/MatchedInfoRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchIgnoredRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchedInfoRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingFilter.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java, src/main/java/com/bookbla/americano/domain/postcard/controller/PostcardController.java, src/main/java/com/bookbla/americano/domain/postcard/repository/custom/PostcardRepositoryCustom.java, src/main/java/com/bookbla/americano/domain/postcard/repository/custom/impl/PostcardRepositoryCustomImpl.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java
=> fix: 엽서 거절 후 14일이 지나지 않았을때 특정 회원의 다른 책이 안나오던 문제 해결

src/main/java/com/bookbla/americano/domain/postcard/repository/custom/impl/PostcardRepositoryCustomImpl.java
=> fix: 엽서 거절 필터링 NPE 해결

build.gradle, src/main/java/com/bookbla/americano/base/handler/GlobalExceptionHandler.java, src/main/java/com/bookbla/americano/domain/auth/controller/dto/response/LoginResponse.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/Member.java, src/main/java/com/bookbla/americano/domain/sendbird/controller/SendbirdController.java, src/main/java/com/bookbla/americano/domain/sendbird/controller/dto/SendbirdResponse.java, src/main/java/com/bookbla/americano/domain/sendbird/service/SendbirdService.java
=> feat: Sendbird 유저/유저토큰 생성 API

src/main/java/com/bookbla/americano/domain/member/service/MemberProfileService.java, src/main/java/com/bookbla/americano/domain/member/service/MemberService.java, src/main/java/com/bookbla/americano/domain/member/service/MemberStyleService.java, src/main/java/com/bookbla/americano/domain/sendbird/service/SendbirdService.java, src/test/java/com/bookbla/americano/domain/member/service/MemberServiceTest.java
> test 주석처리한 부분은 코드는 현재 sendbird 테스트를 만들지않아서.. 추후 작성해두겠습니다
>
=> feat: Sendbird에 닉네임 및 프로필사진 변경 적용

src/main/java/com/bookbla/americano/base/config/AuthConfig.java
=> fix: AdminInterceptor 경로 추가

src/main/java/com/bookbla/americano/base/config/AuthConfig.java
=> fix: AdminInterceptor 경로 삭제

src/main/java/com/bookbla/americano/domain/admin/service/AdminVerificationService.java
=> fix: 트랜잭션 격리수준 변경

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java
=> fix: 매칭 알고리즘 STYLE_NOT_REGISTERED 관련 부분 로그 추가

src/main/java/com/bookbla/americano/domain/postcard/repository/PostcardRepository.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java, src/test/java/com/bookbla/americano/domain/postcard/service/PostcardServiceTest.java
=> Fix: 학생증 미승인 회원 엽서 읽기 불가

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java
=> style: 파라미터명 변경 및 로그 추가

src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberBookmark.java, src/main/java/com/bookbla/americano/domain/sendbird/controller/SendbirdController.java, src/main/java/com/bookbla/americano/domain/sendbird/controller/dto/ChatRequest.java, src/main/java/com/bookbla/americano/domain/sendbird/service/ChatService.java, src/test/java/com/bookbla/americano/domain/sendbird/service/ChatServiceTest.java
> 채팅 수락시 수락한 사람의 책갈피가 30개 소모됩니다
>
=> feat: 채팅 수락 API

src/main/java/com/bookbla/americano/domain/test/controller/TestController.java, src/main/java/com/bookbla/americano/domain/test/controller/dto/response/TestLoginResponse.java
=> fix: test login api 수정

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 새로고침시 NPE 문제 해결

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: NPE 문제 해결

src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberBookmark.java, src/main/java/com/bookbla/americano/domain/sendbird/controller/SendbirdController.java, src/main/java/com/bookbla/americano/domain/sendbird/controller/dto/EntryRequest.java, src/main/java/com/bookbla/americano/domain/sendbird/service/ChatService.java, src/test/java/com/bookbla/americano/domain/sendbird/service/ChatServiceTest.java
=> feat: 채팅 거절 API

src/main/java/com/bookbla/americano/domain/admin/service/AdminMarketingService.java, src/main/java/com/bookbla/americano/domain/notification/enums/PushAlarmForm.java
=> fix: 푸시 알림 수정 및 로그 기록

src/main/java/com/bookbla/americano/domain/admin/service/AdminMarketingService.java, src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberPushAlarm.java
=> fix: MemberId 비교 시 Objects.equals() 로 변경

src/main/java/com/bookbla/americano/domain/matching/exception/MemberMatchingExceptionType.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
> 기획자의 식사가 뜬 후 새고고침시 새로운 매칭정보가 있으면 새로운 매칭정보를 보여줍니다
NOT_FOUND와 BAD_REQUEST를 나눠서 처리했습니다
>
=> fix: 매칭 예외사항 수정

src/main/java/com/bookbla/americano/domain/matching/controller/MemberMatchingController.java, src/main/java/com/bookbla/americano/domain/matching/exception/MemberMatchingExceptionType.java, src/main/java/com/bookbla/americano/domain/matching/repository/MemberMatchingRepository.java, src/main/java/com/bookbla/americano/domain/matching/repository/entity/MemberMatching.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java, src/main/java/com/bookbla/americano/domain/member/service/MemberReportService.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java, src/main/java/com/bookbla/americano/domain/quiz/service/QuizQuestionService.java, src/test/java/com/bookbla/americano/domain/postcard/service/PostcardServiceTest.java
> 기획자의 식사카드 후 새로고침시 새로운 매칭정보가 있으면 isInvitationCard = true로 만들었습니다
>
=> fix: 기획자의 식사카드 후 새로운 매칭정보에 따른 isInvitationCard 수정

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 매칭정보 업데이트 수정

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: updateCurrentMatchedInfo()가 엔티티에 반영되지 않는 문제

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 홈화면 소개카드 안뜨는 문제 및 리팩토링

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 기획자의 식사 카드 이후 새로운 매칭정보 여부에 따라 isInvitationCard 처리

.github/workflows/Deploy-prod-v1.yml, .gitmodules
앱 서비스의 경우 플레이스토어와 앱스토어 두 곳이 동시에 업데이트 되지 않아서 애를 먹는 경우를 많이 봤슴니다
실제 우리도 플레이스토어가 앱스토어보다 약 한달 늦게 올라오기두 했구용...
채팅 들어간 버전이 두 스토어에 모두 올라가기 전까지 aws 리소스를 냅두다가
모두 배포되면 aws 리소스를 지우면 될 것 같으유
지금 앱스토어에 올라가있는 친구는 prod로 냅두고
prod-v1을 새로 만들어서 **main 브랜치**에 머지하면 배포되도록 작업해놨슴니다
V1용 github action sercret은 GCP 작업하시는 분이 넣어주심 될 것 같아요
application-prod-v1 에서 새로 바뀐 내역
- DB 주소(직접 입력해야함)
- jwt secret key
=> feat: prod-v1용 배포파일 및 application-yml 설정

.github/workflows/Deploy-prod-v1.yml, Dockerfile-prod-v1, src/main/java/com/bookbla/americano/base/config/SwaggerConfig.java, src/main/java/com/bookbla/americano/domain/test/controller/TestContextBlocker.java
=> feat: prod-v1 도커파일 생성

src/main/java/com/bookbla/americano/domain/admin/service/AdminVerificationService.java
=> fix: admin 페이지 상태변경 에러 수정

src/main/java/com/bookbla/americano/domain/matching/controller/dto/response/MemberIntroResponse.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 홈에 왔을때 매칭정보가 db에 저장이 안되는 문제 해결

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 홈에 보여져야할 current 정보가 날라가는 버그 수정

src/main/java/com/bookbla/americano/domain/auth/service/AuthService.java
=> feat: 신규 회원 가입 관리자 알림 추가

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 기획자의 식사 카드 후 매칭정보가 있을때 홈에 뜨지않는 오류 수정

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 새로고침 하지 않았는데 초대카드가 안뜨는 문제 해결

src/main/java/com/bookbla/americano/domain/sendbird/service/SendbirdService.java
=> fix: sendbird 유저 생성시 이름, 프사가 안들어가는 버그 수정

src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchIgnoredRepositoryImpl.java, src/main/java/com/bookbla/americano/domain/matching/repository/entity/MatchIgnoredInfo.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java, src/main/java/com/bookbla/americano/domain/postcard/service/dto/request/SendPostcardRequest.java
=> fix: baseEntity 상속 제거 -> ignoredAt 추가 & 엽서 인사말 최대 150자 -> 200자

src/main/java/com/bookbla/americano/domain/matching/repository/entity/MatchIgnoredInfo.java, src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: ignoredAt 업데이트 버그 수정

src/main/java/com/bookbla/americano/domain/sendbird/controller/SendbirdController.java
=> 엽서 소모(엽서 개수 확인) 이후 채팅방 얼림 해제

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java
> - 엽서 수락/대기 중일때 엽서 받은사람 화면에 엽서 보낸사람이 떠서 엽서를 다시보내면 기존 채팅방 내용이 사라지고 다시 생기는 버그 수정
> - 홈에 왔을때 current 매칭정보가 새로고침시 보여지지 않는 버그 수정
>
=> fix: 엽서 및 홈 매칭 버그 수정

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
> 계속 같은 문제입니다.. 마지막 수정이길 바라며,,
>
=> fix: 자정이 되었을때 최우선 매칭정보가 안나오는 버그 수정

src/main/java/com/bookbla/americano/domain/member/exception/MemberEmailExceptionType.java, src/main/java/com/bookbla/americano/domain/member/service/MemberEmailService.java, src/main/java/com/bookbla/americano/domain/notification/event/PostcardAlarmEvent.java, src/main/java/com/bookbla/americano/domain/notification/event/PushAlarmEventHandler.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java
=> fix: ban duplicate email

src/main/java/com/bookbla/americano/domain/sendbird/controller/SendbirdController.java, src/main/java/com/bookbla/americano/domain/sendbird/service/ChatService.java
> application-local.yml, application-dev.yml에 sendbird dev용 토큰 업데이트
>
=> fix: submodule update

src/main/java/com/bookbla/americano/domain/member/service/MemberReportService.java, src/main/java/com/bookbla/americano/domain/sendbird/service/ChatService.java
=> fix: 엽서 거절시 상대방의 다른 책이 안뜨는 버그 수정

src/main/java/com/bookbla/americano/domain/sendbird/service/ChatService.java
=> fix: 엽서 거절시 엽서 상태 안되는 버그 수정

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 자정이 되었을때 초대카드가 안나오는 버그 수정

src/main/java/com/bookbla/americano/domain/member/service/MemberEmailService.java, src/main/java/com/bookbla/americano/domain/member/service/MemberProfileService.java
=> fix: 이메일 중복 검증 버그 수정

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> hotfix: 자정시 초대카드가 뜨지만 다른 페이지 갔다오면 초대카드가 안뜨는 버그 수정

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: 자정시 매칭정보가 없을때 새로고침 버그 수정

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
=> fix: memberIntroResponse 값 비교 수정

src/main/java/com/bookbla/americano/domain/matching/controller/dto/response/MemberIntroResponse.java
=> fix: memberIntroResponse 값 비교 equals() 오버라이드

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
> 이전에 코드 수정하면서 해당사항이 없어진 부분에서 버그가 발생했네요
> 
> 자정: current_member_id: `null`, current_member_book_id: `null`, isInvitationCard: `true`
> 기획자의 식사 카드: current_member_id: `null`, current_member_book_id: `null`, isInvitationCard: `false`
> 매칭 정보 존재: current_member_id: `value`, current_member_book_id: `value`, isInvitationCard: `false`
> 
> ** current_member_id: `value`, current_member_book_id: `value`, isInvitationCard: `true` 인 상황은 없습니다
>
=> fix: 사용하지 않는 코드로 인한 버그 수정

src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
> 너무 헷갈려서 케이스마다 주석달아놨습니다 나중에 지울 예정입니다..!
>
=> fix: matched_info가 존재할때 새로고침이 안되는 버그 수정

src/main/java/com/bookbla/americano/domain/matching/repository/entity/MemberMatching.java, src/main/java/com/bookbla/americano/domain/member/service/MemberReportService.java, src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java, src/main/java/com/bookbla/americano/domain/quiz/service/QuizQuestionService.java
=> fix: 엽서보냈을때, 독서퀴즈 틀렸을때, 신고했을때 매칭 리셋
