- src/main/java/com/bookbla/americano/base/handler/BaseResponseHandler.java
- src/main/java/com/bookbla/americano/domain/test/controller/TestController.java
- src/main/java/com/bookbla/americano/domain/test/controller/dto/request/TestRequestDTO.java
>
*  test save 실행 시 400에러가 발생하던 문제 수정 -> 기본생성자 추가
* response에 data가 포함되지 않는 에러 발견 -> created는 URI를 기본 인자로 받음, 따로 body에 반환할 객체를 넣어줌
=> 정상 작동
>
> fix: ResponseEntity Created 반환시 400에러 및 데이터 반환하지 않는 에러 수정

- src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberStyleCreateRequest.java
- src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberStyleUpdateRequest.java
- src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberStyleResponse.java
- src/main/java/com/bookbla/americano/domain/member/service/impl/MemberStyleServiceImpl.java
- src/test/java/com/bookbla/americano/domain/member/service/MemberStyleServiceTest.java
> 개인 질문 생성/수정시 개인 질문도 함께 보내도록 수정하였습니다
엽서 보내는데 개인 질문이 필요해서, 따른 엔티티로 빼놨었는데
기획 변경에 따라 스타일 생성/수정시 스타일을 함께 보내도록 API 부분만 변경했습니다
>
> fix: 개인 질문 생성/수정시 개인 질문도 함께 보내도록 수정

- src/main/java/com/bookbla/americano/domain/member/controller/MemberBookController.java
- src/main/java/com/bookbla/americano/domain/member/controller/MemberLibraryController.java
- src/main/java/com/bookbla/americano/domain/member/controller/MemberProfileController.java
- src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberBookUpdateRequest.java
- src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberBookReadResponse.java
- src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberLibraryProfileReadResponse.java
- src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberProfile.java
- src/main/java/com/bookbla/americano/domain/member/service/MemberBookService.java
- src/main/java/com/bookbla/americano/domain/member/service/MemberLibraryService.java
- src/main/java/com/bookbla/americano/domain/member/service/impl/MemberBookServiceImpl.java
- src/main/java/com/bookbla/americano/domain/member/service/impl/MemberLibraryServiceImpl.java
- src/main/java/com/bookbla/americano/domain/quiz/QuizQuestion.java
- src/main/java/com/bookbla/americano/domain/quiz/controller/QuizController.java
- src/main/java/com/bookbla/americano/domain/quiz/controller/dto/request/QuizQuestionUpdateRequest.java
- src/main/java/com/bookbla/americano/domain/quiz/exception/QuizQuestionExceptionType.java
- src/main/java/com/bookbla/americano/domain/quiz/repository/QuizQuestionRepository.java
- src/main/java/com/bookbla/americano/domain/quiz/service/QuizQuestionService.java
- src/main/java/com/bookbla/americano/domain/quiz/service/impl/QuizQuestionServiceImpl.java
- src/test/java/com/bookbla/americano/domain/member/repository/entity/MemberProfileTest.java
> 내 서재 관련 API들을 추가하였습니다
- 프로필 조회 API
- 책 상세 정보 API
- 독서퀴즈 업데이트 API
요렇게 세 개입니다
추가로 프론트 입장에선 API 디자인이 어색해진 부분들이 많은데, 한번 얘기 나눠보면 좋을 것 같습니다~
> 내 서재와 상대방 서재 겹치는 부분이 있어서, 머지 빠르게 하고 태완님이 이어서 작업하실 것 같아요~
> feat: 내 서재 관련 기능 구현

- src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberBook.java
- src/main/java/com/bookbla/americano/domain/quiz/QuizQuestion.java
- src/main/java/com/bookbla/americano/domain/quiz/controller/QuizController.java
- src/main/java/com/bookbla/americano/domain/quiz/controller/dto/response/QuizQuestionReadResponse.java
- src/main/java/com/bookbla/americano/domain/quiz/service/QuizQuestionService.java
- src/main/java/com/bookbla/americano/domain/quiz/service/impl/QuizQuestionServiceImpl.java
> 퀴즈 내용을 조회합니다.
- 자신의 퀴즈면 순서를 고정시켜서 반환합니다. 
- 자신의 퀴즈가 아니면 순서를 랜덤으로 섞어서 반환합니다.
> 궁금한 점
- isOwner함수를 추가하여 본인인지 아닌지 판단하는 기능을 추가했지만. validateOwner함수를 수정하면, 함수의 중복을 제거할 수 있을 것 같은데 어떻게 생각하시나요? (validateOwner을 쓰고있는 부분이 많은 것 같아서 일단 건드리지는 못했습니다.)
```
public boolean isOwner(Member other) {
return this.member.equals(other);
}
```
- 무조건 첫 번째 답을 Answer에 추가하면, 다음 기능은 어떤 용도로 사용되는지 궁금합니다!. (답을 수정해도 FIRST는 바뀌지 않고 first_choice만 바뀌는 것 같습니다.
```
public enum AnswerChoice {
FIRST,
SECOND,
THIRD,
;
}
```
> Feat/quiz - 퀴즈 조회 기능 제작

- src/main/java/com/bookbla/americano/base/entity/BaseInsertEntity.java
- src/main/java/com/bookbla/americano/domain/book/infra/kakao/dto/KakaoBookResponse.java
- src/main/java/com/bookbla/americano/domain/member/controller/MemberBookController.java
- src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberStyleCreateRequest.java
- src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberStyleUpdateRequest.java
- src/main/java/com/bookbla/americano/domain/member/exception/MemberExceptionType.java
- src/main/java/com/bookbla/americano/domain/member/repository/MemberBookRepository.java
- src/main/java/com/bookbla/americano/domain/member/repository/entity/Member.java
- src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberBook.java
- src/main/java/com/bookbla/americano/domain/member/service/MemberBookService.java
- src/main/java/com/bookbla/americano/domain/member/service/impl/MemberBookServiceImpl.java
- src/main/java/com/bookbla/americano/domain/member/service/impl/MemberLibraryServiceImpl.java
- src/main/java/com/bookbla/americano/domain/member/service/impl/MemberStyleServiceImpl.java
- src/main/java/com/bookbla/americano/domain/memberask/controller/dto/request/MemberAskCreateRequest.java
- src/main/java/com/bookbla/americano/domain/memberask/controller/dto/request/MemberAskUpdateRequest.java
- src/test/java/com/bookbla/americano/domain/member/service/impl/MemberBookServiceTest.java
> 디스코드에서 언급된 대표책 삭제시 이전에 등록한 책을 대표책으로 바꾸는 기능을 추가하였습니당
작업내역은
1. `MemberBookService.deleteMemberBook()` 내 로직 추가
2. 회원이 등록한 도서 가져올 때 명시적으로 createdAt 순서로 가져오도록 변경
3. 테스트
입니다
>
> feat: 대표 책 삭제시 가장 이전에 등록한 책을 대표책으로 바꾸는 기능 추가

- src/main/java/com/bookbla/americano/base/log/discord/DiscordMessage.java
- src/main/java/com/bookbla/americano/base/log/discord/ExceptionAppender.java
> 디스코드 상으로 전송되는 에러 메시지 형식을 조금 다듬었습니다
>
전
후
> fix: 에러 로깅 형식 수정

- src/main/java/com/bookbla/americano/domain/member/controller/MemberController.java
- src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberBookProfileResponse.java
- src/main/java/com/bookbla/americano/domain/member/repository/MemberPostcardRepository.java
- src/main/java/com/bookbla/americano/domain/member/repository/custom/MemberRepositoryCustom.java
- src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberRepositoryCustomImpl.java
- src/main/java/com/bookbla/americano/domain/member/service/MemberPostcardService.java
- src/main/java/com/bookbla/americano/domain/member/service/MemberProfileService.java
- src/main/java/com/bookbla/americano/domain/member/service/impl/MemberPostcardServiceImpl.java
- src/main/java/com/bookbla/americano/domain/member/service/impl/MemberProfileServiceImpl.java
- src/main/java/com/bookbla/americano/domain/postcard/controller/PostcardController.java
- src/main/java/com/bookbla/americano/domain/postcard/controller/dto/request/PostcardStatusUpdateRequest.java
- src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/MemberPostcardFromResponse.java
- src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/MemberPostcardResponse.java
- src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/MemberPostcardToResponse.java
- src/main/java/com/bookbla/americano/domain/postcard/enums/PostcardPayType.java
- src/main/java/com/bookbla/americano/domain/postcard/exception/PostcardExceptionType.java
- src/main/java/com/bookbla/americano/domain/postcard/repository/PostcardRepository.java
- src/main/java/com/bookbla/americano/domain/postcard/repository/custom/PostcardRepositoryCustom.java
- src/main/java/com/bookbla/americano/domain/postcard/repository/custom/impl/PostcardRepositoryCustomImpl.java
- src/main/java/com/bookbla/americano/domain/postcard/repository/entity/Postcard.java
- src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java
- src/main/java/com/bookbla/americano/domain/postcard/service/dto/response/PostcardFromResponse.java
- src/main/java/com/bookbla/americano/domain/postcard/service/dto/response/PostcardToResponse.java
- src/main/java/com/bookbla/americano/domain/postcard/service/impl/PostcardServiceImpl.java
> 🏠**Home** 
> - 본인 외 다른 사용자 전체의 list를 보내주는 api 추가(members/all-other-members)
>
> 🧑‍🤝‍🧑**Matching**
> - 보낸 엽서/받은 엽서 조회 API 추가
>🧑‍🤝‍🧑**Matching**(detail)
>- 받은 엽서(postcard/to) - GET
- 사용자 정보 : 사용자 이름, 프로필 사진, 나이, 성별, 스타일, 학교
- 퀴즈 답 정보 : 퀴즈 스코어, 책 제목(리스트), 독서 퀴즈 답(리스트), 개인 질문 답
- 책 제목과 독서 퀴즈 답의 같은 index는 같은 책
>- 보낸 엽서(postcard/from) - GET
- 사용자 정보 : 사용자 이름, 나이, 성별, 학교, 프로필 이미지, 카카오톡 오픈채팅 URL
- 책 정보 : 대표 책(제목 / 작가), 모든 등록 책 이미지 url
- 책 이미지의 0번째 index는 대표 책 이미지
>- 엽서 타입 별 개수 확인(postcard)  - GET
- 무료 postcard 수, 유료 postcard 수
>- 엽서 사용(postcard/{payType}) - PATCH
- payType : FREE / PAY
>- 엽서 상태 업데이트(status/{postcardId}) - POST
- PostcardStatusUpdateRequest : status(PostcardStatus)
>
> **+) 줄맞춤 및 Class 이름, import 정리**
> Feat: Home(다른 사용자 전체 list 전송 api 추가) / Matching(보낸 엽서, 받은 엽서 보기를 위한 api 추가)

- src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberPostcard.java
- src/main/java/com/bookbla/americano/domain/postcard/controller/PostcardController.java
- src/main/java/com/bookbla/americano/domain/postcard/controller/dto/request/PostcardSendValidationRequest.java
- src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/PostcardSendValidateResponse.java
- src/main/java/com/bookbla/americano/domain/postcard/enums/PostcardPayType.java
- src/main/java/com/bookbla/americano/domain/postcard/enums/PostcardStatus.java
- src/main/java/com/bookbla/americano/domain/postcard/exception/PostcardExceptionType.java
- src/main/java/com/bookbla/americano/domain/postcard/repository/PostcardRepository.java
- src/main/java/com/bookbla/americano/domain/postcard/repository/PostcardTypeRepository.java
- src/main/java/com/bookbla/americano/domain/postcard/repository/entity/Postcard.java
- src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java
- src/main/java/com/bookbla/americano/domain/postcard/service/dto/request/SendPostcardRequest.java
- src/main/java/com/bookbla/americano/domain/postcard/service/impl/PostcardServiceImpl.java
- src/main/java/com/bookbla/americano/domain/quiz/repository/QuizQuestionRepository.java
- src/main/java/com/bookbla/americano/domain/quiz/repository/entity/QuizQuestion.java
- src/test/java/com/bookbla/americano/domain/postcard/repository/entity/PostcardTest.java
- src/test/java/com/bookbla/americano/domain/postcard/service/PostcardServiceTest.java
>
1. 엽서 보내기 전 검증용 API를 만들었습니다 
```[POST] /api/postcard/send/validation```
전송 불가능한 경우, 예외를 던져 GlobalExceptionHandler에서 잡아, 기본 응답의 isSuccess 값을 false로 반환하도록 하였슴다
-> 메시지로 이유 던져줍니다
전송 가능한 경우, isRefund (boolean)을 통해, 이전에 보냈으나 거절당한 엽서가 있는지를 확인하도록 하였슴다
2. 엽서 보내기 API를 조금 수정하였습니다
- 유료 추가 대비해서, postcardPayType을 보내도록 하였슴다
- 요청시 memberAskId를 보내야 하던 것을 없애고, 엽서를 보내려는 상대방의 memberId를 보내도록 변경하였슴다(이게 더 편하실 것 같아서...!)
- postCardTypeId를 보내고 있으니, 엽서 이미지 링크를 보낼 필요는 없을 것 같아 imageUrl을 안받도록 하였슴다
- 1번에서 사용하는, 전송 불가능한 경우인지 체크하는 로직을 같이 넣어놨어요
> 2번 엽서 보내기 API 내역이 주현님께서 요번에 작업해주신 부분과 일부 겹치는 것 같습니다(유료엽서, 무료엽서 개수 차감 로직)
요렇게 올라가도 되는지 한 번 확인해주시면 감사하겠습니다..!
> feat: 엽서 전송 확인 API 구현 & 유료 엽서 대응 가능하도록 변경

- src/main/java/com/bookbla/americano/base/utils/ConvertUtil.java
- src/main/java/com/bookbla/americano/domain/admin/controller/AdminController.java
- src/main/java/com/bookbla/americano/domain/admin/controller/dto/response/AdminMemberKakaoRoomResponses.java
- src/main/java/com/bookbla/americano/domain/admin/controller/dto/response/AdminMemberProfileImageResponses.java
- src/main/java/com/bookbla/americano/domain/admin/controller/dto/response/AdminMemberStudentIdResponses.java
- src/main/java/com/bookbla/americano/domain/admin/service/AdminMemberService.java
- src/main/java/com/bookbla/americano/domain/member/controller/MemberProfileController.java
- src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberProfileImageUpdateRequest.java
- src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberProfileOpenKakaoRoomUrlUpdateRequest.java
- src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberProfileUpdateRequest.java
- src/main/java/com/bookbla/americano/domain/member/enums/OpenKakaoRoomStatus.java
- src/main/java/com/bookbla/americano/domain/member/enums/ProfileImageStatus.java
- src/main/java/com/bookbla/americano/domain/member/exception/MemberPostcardExceptionType.java
- src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberPostcard.java
- src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberVerify.java
- src/main/java/com/bookbla/americano/domain/member/service/MemberProfileService.java
- src/main/java/com/bookbla/americano/domain/member/service/dto/MemberProfileDto.java
- src/main/java/com/bookbla/americano/domain/member/service/impl/MemberProfileServiceImpl.java
- src/main/java/com/bookbla/americano/domain/postcard/service/dto/request/SendPostcardRequest.java
- src/main/java/com/bookbla/americano/domain/postcard/service/impl/PostcardServiceImpl.java
- src/test/java/com/bookbla/americano/domain/postcard/service/PostcardServiceTest.java
> 엽서 사용 로직 변경
기존 : 유/무료를 사용자가 직접 선택하게 함
변경 후 : 
1) 무료엽서 개수 확인
2) 있으면 차감 후 종료
3) 없다면 유료엽서 확인
4) 무료/유료 엽서 개수 모두 확인
5) 없다면 예외
6) 유료 엽서 차감
엽서 검증 변경 -> 무료 엽서와 유료 엽서 모두 없다면 예외 던짐
> 프로필 변경시 임시 테이블 사용하도록 변경
>
> fix: 엽서 차감 로직 변경 & 프로필 검증 테이블 적용

- src/main/java/com/bookbla/americano/domain/member/repository/MemberVerifyRepository.java
- src/main/java/com/bookbla/americano/domain/member/service/impl/MemberBookServiceImpl.java
- src/main/java/com/bookbla/americano/domain/member/service/impl/MemberLibraryServiceImpl.java
- src/main/java/com/bookbla/americano/domain/member/service/impl/MemberProfileServiceImpl.java
>
인증 요청시 기존 검증 대기 요청 제거하도록 변경
내 서재에서 검증 요청 여부 확인시 한 개가 아닌 여러개로 받아, 최신 요청을 가지고 오도록 수정
>
> fix: 프로필/카톡방 승인 대기 상태에서 다시 변경 요청하는 경우의 방어로직 추가

- src/main/java/com/bookbla/americano/domain/postcard/repository/custom/impl/PostcardRepositoryCustomImpl.java
> 받은 엽서(postcard/to) 호출 시, 읽기 전(PENDING), 읽음(READ), 수락(ACCEPT) 상태인 엽서만 읽어오도록 수정
> 혹시 DB에 직접 접근하거나, 엽서 상태 변경 시 이상한 값이 들어가 엽서 상태가 이상한 값으로 저장되어 있는 경우, 이상한 상태로 저장 된 엽서도 보내지지 않게 하기 위하여 "읽기 전", "읽음", "수락" 상태 외의 다른 상태는 보내지지 않도록 수정하였습니다. 
> 엽서 상태를 변경하는 api에 이상한 상태로 변경 요청을 하면 Exception(Bad Request)이 나도록 되어있긴 하지만, 혹시나 저장 될 수 있을 것 같아 "받은 엽서"에서 읽을 수 있는 엽서 상태가 아니라면 보내지 않도록 수정하였습니다.
> Fix: 매칭_받은 엽서(postcard/to) api 수정

- src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberRepositoryCustomImpl.java
- src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/MemberPostcardFromResponse.java
- src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/MemberPostcardToResponse.java
- src/main/java/com/bookbla/americano/domain/postcard/service/impl/PostcardServiceImpl.java
>[Home]`all-other-members` api 수정
>- all-other-members 호출 시 **COMPLETE** 상태의 회원들만 보이도록 수정
>
>[Matching] 수락 되지 않은 엽서에서 상대방의 이름 보이지 않도록 수정
>- 받은 엽서, 보낸 엽서 조회 시, 엽서가 **ACCEPT** 상태일때만 상대방의 이름이 모두 뜨도록 수정
>- **ACCEPT** 상태가 아닌 경우에는 `{성}OO`으로 보여지도록 수정
>
> fix: (Home)`all-other-members` api 수정 및 (Matching)이름 마스킹 수정

- src/main/java/com/bookbla/americano/domain/memberask/controller/MemberReplyController.java
- src/main/java/com/bookbla/americano/domain/memberask/controller/dto/request/MemberReplyUpdateRequest.java
- src/main/java/com/bookbla/americano/domain/memberask/controller/dto/response/MemberReplyResponse.java
- src/main/java/com/bookbla/americano/domain/memberask/exception/MemberReplyExceptionType.java
- src/main/java/com/bookbla/americano/domain/memberask/repository/entity/MemberReply.java
- src/main/java/com/bookbla/americano/domain/memberask/service/MemberReplyService.java
- src/main/java/com/bookbla/americano/domain/memberask/service/impl/MemberReplyServiceImpl.java
>### member-reply controller 추가 (`/members/member-reply` )
>    - **읽기** - GET(`/{postcardId}`)
>        - **응답** : memberReplyId, askContent(질문), replyContent(답변)
>        - 해당 id의 엽서가 없을 때, `PostcardExceptionType.INVALID_POSTCARD`
>        - 해당 엽서의 보낸 사람이 본인이 아닐 때, `PostcardExceptionType.ACCESS_DENIED_TO_POSTCARD`
>        - 해당 엽서에 등록 된 개인 질문이 없을 때, `MemberAskExceptionType.NOT_REGISTERED_MEMBER`
>    - **수정** - PUT
>        - **요청 Body** : postcardId(엽서 Id), content(수정할 답변)
>        - 해당 id의 엽서가 없을 때, `PostcardExceptionType.INVALID_POSTCARD`
>        - 해당 엽서의 보낸 사람이 본인이 아닐 때, `PostcardExceptionType.ACCESS_DENIED_TO_POSTCARD`
>        - 해당 엽서의 상태가 `PENDING` 상태가 아닐 때, `MemberReplyExceptionType.IMMUTABLE_POSTCARD`
>
> feat: member-reply 읽기, 수정 api 추가

- src/main/java/com/bookbla/americano/base/config/AsyncConfig.java
- src/main/java/com/bookbla/americano/domain/admin/service/AdminMarketingService.java
- src/main/java/com/bookbla/americano/domain/notification/service/AlarmService.java
- src/main/java/com/bookbla/americano/domain/notification/service/PostcardAlarmEvent.java
- src/main/java/com/bookbla/americano/domain/notification/service/PostcardPushAlarmEventListener.java
- src/main/java/com/bookbla/americano/domain/notification/service/PushAlarmSendAllEvent.java
- src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java
> 엽서 전송/수락과 알림 발송이 한 트랜잭션 안에 묶여있어서
사용자 알림 발송이 실패했을시, 엽서 수락/전송이 아예 불가능하도록 되어있습니다
이에 트랜잭션도 분리하였고, 아예 다른 관심사인 것 같아서 이벤트로 받게 해놨어요
비동기도 붙여놨는데, 스레드 풀 설정은 추후에 해두려 합니당
>
> fix: 엽서 전송/수락과 알림 발송을 분리

- src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberBookmark.java
- src/main/java/com/bookbla/americano/domain/school/controller/dto/response/InvitationResponse.java
- src/main/java/com/bookbla/americano/domain/school/event/InvitationEventListener.java
- src/main/java/com/bookbla/americano/domain/school/repository/entity/Invitation.java
- src/main/java/com/bookbla/americano/domain/school/service/InvitationService.java
> 학교 축제에서 사용할 임시축제초대코드를 발급하는 기능을 구현하였습니다(도현님 요청)
기능 설명
- 축제때 하실 이벤트를 위한 임시 기능입니다
- 이 초대코드를 입력하면 책갈피 105개 지급합니당
> 여성회원 초대코드 입력시 책갈피 발급 정책이 변경돼서, 해당 내역도 반영해놨습니다
> feat: 축제에서 사용할 이벤트 초대코드 기능 구현

- src/main/java/com/bookbla/americano/domain/auth/infra/kakao/KakaoOAuth2Provider.java
- src/main/java/com/bookbla/americano/domain/member/exception/MemberProfileExceptionType.java
- src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberProfile.java
- src/test/java/com/bookbla/americano/domain/member/repository/entity/MemberProfileTest.java
[AS-IS]
(FE) 인가 코드 발급 및 로그인 요청
(BE) 인가 코드 이용 액세스 토큰 발급
(BE) 액세스 토큰 이용 사용자 정보 획득
(BE) 자체 토큰 발급 및 로그인 처리
[TO-BE]
(FE)~~인가 코드 발급 및 백엔드 로그인 요청~~ => **액세스 토큰 발급 받아 로그인 요청**
~~(BE) 인가 코드 이용 액세스 토큰 발급~~
(BE) 액세스 토큰 이용 사용자 정보 획득
(BE) 자체 토큰 발급 및 로그인 처리
>
카카오 로그인 API 호출 DTO 필드를 accessToken으로 수정하여 컨트롤러와 서비스를 따로 만들려고 했으나, 
필드명 하나 바꿔줬다고 쓸데없이 중복코드가 발생하는 것 같아 기존 API 그대로 사용하고,
프론트에서 **액세스 토큰**을 기존처럼 동일 API에 authCode로 넘기는 방식으로 전파할게요~!
* 닉네임 변경 검증 조건 추가 간단해서 해당 PR에 같이 올릴게요..ㅎㅎ
>
> 카카오 인증 절차 변경 & 닉네임 변경 검증 조건 추가

- src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberBookmark.java
- src/main/java/com/bookbla/americano/domain/postcard/controller/PostcardController.java
- src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/MemberPostcardToResponse.java
- src/main/java/com/bookbla/americano/domain/postcard/repository/custom/PostcardRepositoryCustom.java
- src/main/java/com/bookbla/americano/domain/postcard/repository/custom/impl/PostcardRepositoryCustomImpl.java
- src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java
- src/main/java/com/bookbla/americano/domain/postcard/service/dto/response/PostcardToResponse.java
- src/main/java/com/bookbla/americano/scheduler/ScheduleWorker.java
>### 받은 엽서 조회(/postcard/to) api 수정
>- 한국 나이로 나이 변경
>- 엽서 읽기(READ) 시 책갈피 5개 사용으로 수정
>- 엽서 거절로 상태 변경 시 35개 환불
>- 엽서를 받은 날짜 포함 3일이 지나면 엽서 거절로 상태 변경 및 보낸 사람에게 책갈피 환불
>    - 만약, 9/8에 보낸 엽서 중 PENDING/READ 상태에 있는 엽서 들은 9/11일 0시 0분에 모두 거절 됨
>- 받은 엽서 조회(/postcard/to) api에서 전달하는 데이터 수정(책 관련 데이터 모두 보내지 않도록 수정.)
>    - 엽서 ID
>    - 보낸 사람 Id, 닉네임, 프로필 이미지, 나이, 성별, 스타일 정보, 학교 이름
>    - 엽서를 받은 시간, 엽서 상태, 엽서 이미지
>### 보낸 엽서 조회(/postcard/from) api 수정
>- DB 스키마 변경되면서 오류 발생하던 부분 수정
> 보낸 엽서 조회(/postcard/from) api는 현재 사용하지 않지만 지우지는 않고, api가 정상 작동하도록 수정해두었습니다.
> feat: 받은 엽서/보낸엽서 조회api 수정

- src/main/java/com/bookbla/americano/domain/member/enums/StudentIdImageStatus.java
- src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberProfile.java
`studentIdImageStatus`에 enum 타입에 학생증 사진이 등록되지 않은 상태인 `UNREGISTER`를 추가했습니다!
>
>
> fix: 학생증 사진을 등록되지 않은 상태 추가(UNREGISTER)

- src/main/java/com/bookbla/americano/base/config/WebSocketConfig.java
This commit adds a new endpoint "/chat/ws/connect" for connecting to the chat WebSocket. This endpoint allows clients to establish a WebSocket connection for real-time chat functionality. The "setAllowedOrigins("*")" method is used to allow connections from any origin.
>
>
> feat: Add endpoint for connecting to chat WebSocket

- src/main/java/com/bookbla/americano/base/config/AuthConfig.java
- src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberBookmark.java
- src/main/java/com/bookbla/americano/domain/payment/controller/PaymentController.java
- src/main/java/com/bookbla/americano/domain/payment/controller/PaymentSubscriber.java
- src/main/java/com/bookbla/americano/domain/payment/controller/docs/PaymentControllerDocs.java
- src/main/java/com/bookbla/americano/domain/payment/controller/dto/request/AppleNotificationRequest.java
- src/main/java/com/bookbla/americano/domain/payment/controller/dto/request/ApplePaymentInAppPurchaseRequest.java
- src/main/java/com/bookbla/americano/domain/payment/controller/dto/request/GooglePaymentInAppPurchaseRequest.java
- src/main/java/com/bookbla/americano/domain/payment/exception/PaymentExceptionType.java
- src/main/java/com/bookbla/americano/domain/payment/infrastructure/apple/AppleLibraryProvider.java
- src/main/java/com/bookbla/americano/domain/payment/infrastructure/apple/ApplePaymentStrategy.java
- src/main/java/com/bookbla/americano/domain/payment/repository/Payment.java
- src/main/java/com/bookbla/americano/domain/payment/repository/PaymentNotification.java
- src/main/java/com/bookbla/americano/domain/payment/repository/PaymentNotificationRepository.java
- src/main/java/com/bookbla/americano/domain/payment/repository/PaymentRepository.java
- src/main/java/com/bookbla/americano/domain/payment/service/PaymentService.java
- src/main/java/com/bookbla/americano/domain/payment/service/PaymentStrategies.java
- src/main/java/com/bookbla/americano/domain/payment/service/PaymentStrategy.java
- src/main/java/com/bookbla/americano/scheduler/ScheduleWorker.java
> 
애플 환불 구현했습니다
애플의 인앱결제 환불 플로우는 다음과 같아요
```mermaid
sequenceDiagram 
Autonumber
participant Client
participant Apple Server
participant Bookbla Server
Client->>Apple Server: 환불 신청
Apple Server->>Bookbla Server: 인앱 결제 공지
Bookbla Server->>Bookbla Server: 환불 검증
Bookbla Server->>Apple Server: 200번 || 400번
Apple Server->>Client: 환불 결과 알림
```
애플로 부터 받은 응답이 유효할 경우, 200번대 응답을 주면 되고
실패할 경우, 400번대를 던져주면 됩니다
애플에서 받은 모든 정보를 DB에 저장해두고 싶어서, 최대한 비즈니스 단에서 예외를 던지지 않는 방식으로 만들어놨습니다
덕분에 컨트롤러단에서 분기를 타는 진짜 해괴한 방식이 되었네요...ㅋㅋㅋ
환불 신청 내역을 애플 개발자 계정에서 확인할 수 있다면... 제일 좋은 방법일 것 같은데, 묘수가 잘 떠오르지 않습니다
돈 관련된 로직이다보니 여유 되신다면 꼭 리뷰 부탁드리겠습니다!
> https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/handling_refund_notifications
> feat: 애플 인앱결제 환불 구현

- src/main/java/com/bookbla/americano/domain/book/infra/kakao/dto/KakaoBookResponse.java
- src/main/java/com/bookbla/americano/domain/book/service/dto/BookSearchResponses.java
- src/main/java/com/bookbla/americano/domain/member/controller/MemberController.java
- src/main/java/com/bookbla/americano/domain/member/controller/dto/request/MemberStatusUpdateRequest.java
- src/main/java/com/bookbla/americano/domain/member/service/MemberService.java
- src/main/java/com/bookbla/americano/domain/payment/repository/Payment.java
- src/main/java/com/bookbla/americano/domain/payment/repository/PaymentNotification.java
- src/main/java/com/bookbla/americano/domain/school/repository/entity/Invitation.java
- src/main/java/com/bookbla/americano/domain/school/repository/entity/InvitationStatus.java
- src/main/java/com/bookbla/americano/domain/school/service/InvitationService.java
>
- Payment Entity 내 json을 저장하기 위한 information 필드 TEXT 타입 명시
- 매칭 비활성화시 사유 저장
- 카카오 도서검색시 중복 데이터 제거
- 초대코드 입력시 축제 임시 초대코드 중복 입력 가능했던 것 수정
>
> fix: 9/18 트러블 슈팅 내역 반영

- src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberVerifyRepositoryCustomImpl.java
- src/main/java/com/bookbla/americano/domain/postcard/repository/custom/impl/PostcardRepositoryCustomImpl.java
> aws 접속하여 로그보고 매칭 필터링을 위한 querydsl 수정했습니다
원하는 조건이 and()에서 일부 빠져서 다시 수정했습니다 
>
> fix: 학생증 및 거절 필터링 쿼리 수정

- src/main/java/com/bookbla/americano/domain/matching/repository/MatchExcludedRepository.java
- src/main/java/com/bookbla/americano/domain/matching/repository/MatchIgnoredRepository.java
- src/main/java/com/bookbla/americano/domain/matching/repository/MatchedInfoRepository.java
- src/main/java/com/bookbla/americano/domain/matching/repository/custom/MatchedInfoRepositoryCustom.java
- src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchedInfoRepositoryImpl.java
- src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MemberMatchingRepositoryImpl.java
- src/main/java/com/bookbla/americano/domain/matching/repository/entity/MatchExcludedInfo.java
- src/main/java/com/bookbla/americano/domain/matching/repository/entity/MatchIgnoredInfo.java
- src/main/java/com/bookbla/americano/domain/matching/repository/entity/MatchedInfo.java
- src/main/java/com/bookbla/americano/domain/matching/repository/entity/MemberMatching.java
- src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java
- src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingFilter.java
- src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
- src/main/java/com/bookbla/americano/domain/matching/service/dto/MemberRecommendationDto.java
- src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java
- src/main/java/com/bookbla/americano/domain/quiz/service/QuizQuestionService.java
기존 MatchedInfo 에 모든 필터링된 매칭 정보를 저장하는 방식은 유저가 증가할수록 기하급수적으로 디비에 부담이 갈 거라 생각했습니다
MemberMatching 엔티티를 필두로
1. 필터링과 알고리즘을 거친 매칭 정보를 저장하는 `MatchedInfo`
2. 추천 아이디와 책을 무시하는 `MatchIgnoredInfo`
3. 추천 아이디를 무시하는 `MatchExcludedInfo`
로 분리했습니다.
이에 따른 쿼리 및 dto 단에도 수정이 생겼습니다
> fix, refactor: 매칭 알고리즘 수정

- src/main/java/com/bookbla/americano/domain/member/exception/MemberProfileExceptionType.java
- src/main/java/com/bookbla/americano/domain/member/repository/entity/Member.java
- src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java
- src/test/java/com/bookbla/americano/domain/postcard/service/PostcardServiceTest.java
> 최초 가입 후 학생증이 인증되지 않은 상태에서 엽서를 보낼 수 없는 로직 추가
>
> feat: 엽서 보내는 회원의 학생증 인증 상태 검증 추가

- src/main/java/com/bookbla/americano/domain/matching/repository/MatchIgnoredRepository.java
- src/main/java/com/bookbla/americano/domain/matching/repository/custom/MatchIgnoredRepositoryCustom.java
- src/main/java/com/bookbla/americano/domain/matching/repository/custom/MatchedInfoRepositoryCustom.java
- src/main/java/com/bookbla/americano/domain/matching/repository/custom/MemberMatchingRepositoryCustom.java
- src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchIgnoredRepositoryImpl.java
- src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchedInfoRepositoryImpl.java
- src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MemberMatchingRepositoryImpl.java
- src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingFilter.java
- src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
- src/main/java/com/bookbla/americano/domain/member/repository/custom/MemberBlockRepositoryCustom.java
- src/main/java/com/bookbla/americano/domain/member/repository/custom/impl/MemberBlockRepositoryImpl.java
- src/main/java/com/bookbla/americano/domain/postcard/repository/custom/PostcardRepositoryCustom.java
- src/main/java/com/bookbla/americano/domain/postcard/repository/custom/impl/PostcardRepositoryCustomImpl.java
> 홈에 추천해줄 memberId를 단계별로 필터링 후 필터링된 memberId의 memberBookId를 모두 뽑아 MatchIgnoredInfo를 필터링하여 최종적으로 memberId, memberBookId를 뽑아냄
=> MatchIgnoredInfo에서 memberId, memberBookId를 필터링하기 복잡했던 문제 해결 ✔️
>
> 1️⃣ ) 최소 조건: 제외 및 회원 상태 으로 추출한 추천 memberIds
2️⃣ ) 차단한 회원 필터링 후 추천 memberIds
3️⃣ ) 엽서 거절 필터링 후 추천 memberIds
4️⃣ ) 3️⃣을 통해 나온 memberIds에 해당하는 모든 memberBookIds - MatchIgnoredInfo에 있는 memberId, memberBookId
> 4️⃣ 의 경우 
> 1. "memberMatchingRepository.getAllMatching() 에서matchIgnoredRepository.getIgnoredMemberIdsAndIgnoredMemberBookIdByMemberId()를 제거하는 방법"으로 memberMatchingFilter의 memberIgnoredFiltering()에서 두개를 사용해서 로직 구현 
> 2. 위의 두 레포를 가져와 로직 구현한 부분을 하나로 합친 memberMatchingRepository.getMatchingInfo()를 만들어
memberMatchingFilter의 finalFiltering()에서 로직 구현
**Q. 현재 1번은 주석 처리, 2번으로 구현되어있는데 유지보수나 유연성때문에 1번을 남겨둔 …
> refactor: memberId, memberBookId 필터링 -> memberId 필터링 후 memberId에 해당되는 memberBookId 필터링

- src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchedInfoRepositoryImpl.java
> @khyu2 홈매칭 쿼리 수정으로 인해 회원 상태변경 및 신고, 무시에 따른 matchedInfo에 반영되어 pop되는 부분도 다시 수정해야합니다
>
> fix: refresh시 pop할때 발생하는 에러

- src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java
- src/main/java/com/bookbla/americano/domain/matching/service/dto/MatchingSimilarityWeightConstants.java
> 회원가입 시 받는 정보를 최대한 활용하도록 알고리즘 매칭 가중치를 세분화했습니다
기본적인 흐름입니다
같은 책: 0.6 (매우 중요한 항목)
리뷰 글자수 60자 이상: 0.5 (매우 중요한 항목)
나이 차이 3 이하: 0.4 (중요 항목)
같은 학교: 0.3 (중간 중요 항목)
흡연 여부 일치: 0.2 (중간 중요 항목)
같은 저자: 0.1 (덜 중요한 항목)
나이 차이 3 초과: 0.1 (덜 중요한 항목)
같은 학교 같은 책: 1.0
같은 학교 같은 저자: 0.4
같은 학교 : 0.2
같은 학교 흡연 여부 동일: 0.3
다른 학교 같은 책: 0.6
다른 학교 같은 저자: 0.1
다른 학교 흡연 여부 동일: 0.2
리뷰 길이 체크: 0.5
비슷한 나이대 체크: 0.4
> fix: 매칭 알고리즘 가중치 세분화

- src/main/java/com/bookbla/americano/domain/matching/repository/MemberMatchingRepository.java
- src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java
- src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
- src/main/java/com/bookbla/americano/scheduler/ScheduleWorker.java
> `@Scheduled` 를 사용해서 매일 자정에 필터링된 회원 정보를 날리도록 구현했습니다
1. matchedInfo 테이블 전부 삭제
2. current_matched_member_id, current_matched_member_book_id 를 NULL 로 변경 -> 이후 NULL 이면 새로 추천 회원을 뽑기
> feat: 00시에 필터링된 사용자를 제거하도록 변경

- src/main/java/com/bookbla/americano/domain/matching/repository/entity/MatchedInfo.java
- src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingAlgorithmFilter.java
- src/main/java/com/bookbla/americano/domain/matching/service/dto/MatchingSimilarityWeightConstants.java
- src/test/java/com/bookbla/americano/domain/matching/service/dto/MatchingSimilarityWeightConstantsTest.java
- src/test/java/com/bookbla/americano/domain/postcard/service/PostcardServiceTest.java
합연산
- 같은 학교 0.3
- 같은 흡연 0.2
- 동일 나이대 0.2
상수 합연산 후 곱연산 적용
- 리뷰 길이 (20~) 차등 부여 0.1~1.0
- 100글자 이상 - 1.0
- 90 이상 - 0.9
- 80 이상 - 0.8
- 70 이상 - 0.7
- …
- 20글자 - 0.2
- 그 밑 - 0.05
- 같은 책 2.0
- 같은 저자 1.5
- else 1.0
> fix: 알고리즘 가중치 로직 변경(곱연산 적용)

- src/main/java/com/bookbla/americano/domain/postcard/repository/custom/impl/PostcardRepositoryCustomImpl.java
> 기획에서 이미 읽은 엽서는 우편함에서 보여주지 않는 것으로 처리해서 Status - READ, ACCEPT상태의 엽서는 조건에서 제외했습니다!
>
> feat: 받은 엽서 중 이미 확인한 엽서는 조회하지 않게 변경

- src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/PostcardReadResponse.java
- src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java
- src/main/java/com/bookbla/americano/domain/postcard/service/dto/request/SendPostcardRequest.java
- src/main/java/com/bookbla/americano/domain/postcard/service/dto/response/SendPostcardResponse.java
- src/test/java/com/bookbla/americano/domain/postcard/service/PostcardServiceTest.java
`POST postcard/send`
```
req
{
"postcardTypeId": 0, 
“sendMemberId”: 0, - 추가
“sendMemberName”: “string”, - 추가
"receiveMemberId": 0,
"receiveMemberBookId": 0,
"memberReply": "string",
"channelUrl": "string" - 삭제
}
```
`POST postcard/read/{postcardId}`
```
res
{
"channelUrl": "string" 삭제
“sendMemberId”: 0, - 추가
“sendMemberName”: “string”, - 추가
"receiveMemberId": 0, - 추가
"receiveMemberBookId": 0, - 추가
"memberReply": "string", - 추가
}
```
> fix: 채팅방 생성 로직 변경에 따라 api req, res 변경

- src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/PostcardReadResponse.java
- src/main/java/com/bookbla/americano/domain/postcard/service/dto/request/SendPostcardRequest.java
- src/test/java/com/bookbla/americano/domain/postcard/service/PostcardServiceTest.java
> fix: 엽서 보내기 로직에서 sendMemberId Param 제거

- src/main/java/com/bookbla/americano/domain/matching/controller/dto/response/MemberIntroResponse.java
- src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
> 간단하게 방어 로직 구현했습니다
자정에 홈 화면 접속 시 currentMatchedInfo가 저장되는데 이러면 새로운 사람 만나기(refresh) 시에 current 정보가 날라가도록 작성되어 있었는데  
이를 자정에 홈 화면 접속 시 isInvitationCard를 보내줘서 홈 화면에 초대 카드를 띄워주도록 변경했습니다
> fix: 자정에 current 정보가 날라가는 버그 수정

- src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
> fix: 엽서퀴즈 틀리고 홈왔을때 그 매칭정보가 다시 뜨는 문제 해결

- src/main/java/com/bookbla/americano/domain/matching/repository/custom/impl/MatchIgnoredRepositoryImpl.java
> 다른사람만나기 후 7일뒤에 같은 매칭정보를 또 새로고침할 수 있다는 점을 간과했습니다..
>
> fix: MatchIgnoredInfo 쿼리 수정

- src/main/java/com/bookbla/americano/domain/notification/event/PushAlarmEventHandler.java
- src/main/java/com/bookbla/americano/domain/postcard/controller/PostcardController.java
- src/main/java/com/bookbla/americano/domain/postcard/controller/dto/response/PostcardReadResponse.java
- src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java
- src/main/java/com/bookbla/americano/domain/sendbird/controller/SendbirdController.java
- src/main/java/com/bookbla/americano/domain/sendbird/controller/dto/request/EntryRequest.java
- src/main/java/com/bookbla/americano/domain/sendbird/service/ChatService.java
- src/main/java/com/bookbla/americano/domain/sendbird/service/SendbirdService.java
- src/test/java/com/bookbla/americano/domain/sendbird/service/ChatServiceTest.java
> Sendbird 메타데이터로 postcardId를 넣어, 채팅 수락/거절시 postcardId를 requset로 받아 postcard 상태 변경 및 책갈피 개수 업데이트 하도록 만들었습니다.
>
> fix: 엽서(채팅) 수락/거절시 postcard 상태 변경 및 책갈피 개수 업데이트

- src/main/java/com/bookbla/americano/domain/notification/event/PostcardAlarmEvent.java
- src/main/java/com/bookbla/americano/domain/notification/event/PushAlarmEventHandler.java
- src/main/java/com/bookbla/americano/domain/postcard/service/PostcardService.java
- src/main/java/com/bookbla/americano/domain/sendbird/service/ChatService.java
>
기존
```java
public class PostcardAlarmEvent {
private final Member pushAlarmSendMember;
private final Member pushAlarmTargetMember;
}
```
변경 후
```java
public class PostcardAlarmEvent {
private final String messageBodyElement;
private final Member targetMember;
}
```
헷갈려 오기입하는 경우가 많더라구요
메시지 보내는 대상에 대해서만 Member로 받도록 수정했습니다
>
> refactor: 푸시알림 이벤트 핸들러 파라미터 수정

- src/main/java/com/bookbla/americano/domain/member/controller/dto/response/MemberInvitationRewardResponse.java
- src/main/java/com/bookbla/americano/domain/member/repository/entity/MemberModal.java
- src/main/java/com/bookbla/americano/domain/school/repository/entity/Invitation.java
- src/main/java/com/bookbla/americano/domain/school/repository/entity/InvitationType.java
- src/main/java/com/bookbla/americano/domain/school/service/InvitationService.java
- src/main/java/com/bookbla/americano/domain/school/service/dto/InvitationConstants.java
- src/test/java/com/bookbla/americano/domain/school/service/InvitationServiceTest.java
> 이번 사전 모집에 사용할 얼리버드 초대코드를 이벤트 코드로 추가하므로써 기존 축제 코드와 분리하여 작성함
> 앞으로 다양한 축제와 이벤트가 열릴 것으로 보아 축제와 이벤트 관련 초대코드 및 책갈피 보상을 상수클래스(InvitationConstants)에 모아 작성함
>
> feat: 사전 모집 이벤트 초대코드 추가

- src/main/java/com/bookbla/americano/domain/matching/controller/dto/response/MemberIntroResponse.java
- src/main/java/com/bookbla/americano/domain/matching/service/MemberMatchingService.java
> matched_info 정보를 getHomeMatch()에서 member_matching에 업데이트하니 또 다른 페이지 갔다왔을때 초대카드가 없어지는 문제 발생하여  refreshMemberMatching()에서 하게끔 수정 
>
> fix: matched_info 정보를 member_matching에 업데이트 하는 부분을 refresh에서 하게끔 수정
